### ISSUE TITLE
[Need Help]请问一下调用run函数为什么无法自动携带全局的分页参数

### ISSUE THREAD

**Issue by XiaoHuoZZ** [AttoJS/vue-request#101]
### 问题描述 Problem Description

我设置了全局分页参数
```typescript
import { setGlobalOptions } from 'vue-request'
// 设置分页参数
setGlobalOptions({
    pagination: {
        currentKey: 'pageNo',
        pageSizeKey: 'pageSize',
        totalKey: 'total',
        totalPageKey: 'pages',
    },
});
```
在第一次使用userPagination函数时是可以携带分页参数访问的
```typescript
const {data, current, pageSize, total, run} = usePagination(definition.getData,{
  formatResult: res => res.data.records,
})
```
但是有个地方我需要手动再去执行一次网络请求
```typescript
const onFinish = (values: QueryState) => {
  run(values)
}
```
这时候的网络请求就不会携带分页参数了，请问有什么好的解决办法吗？谢谢

**Comment by John60676** [comment]
翻页可以用 [changeCurrent](https://www.attojs.com/api/pagination.html#changecurrent)， 如果只是想重新请求但是保留当前页，可以用 [refresh](https://www.attojs.com/api/#refresh)

**Comment by XiaoHuoZZ** [comment]
> > 翻页可以用 [changeCurrent](https://www.attojs.com/api/pagination.html#changecurrent)， 如果只是想重新请求但是保留当前页，可以用 [refresh](https://www.attojs.com/api/#refresh)
> 
> 感谢您的回答，使用了refresh之后的确可以携带之前的分页参数，但是它会保留之前的defaultparams,。因为我这里是需求是条件搜索查询请求，条件变了，需要进行触发。请问如何既能携带旧分页参数又能携带新的条件参数呢

我懂了，可以这样写
```typescript
const onFinish = (values: QueryState) => {
  run({
    pageNo: current.value,
    pageSize: pageSize.value,
    ...formState
  })
}
```

**Comment by John60676** [comment]
直接解构 `params` 也是可以的
