### ISSUE TITLE
如果一个页面中有多个列表，怎么区分每个列表的数据？或者把每个列表的数据创建各自的对象？

### ISSUE THREAD

**Issue by heishuang** [AttoJS/vue-request#103]
如下，如果一个页面有多个列表，都使用usePagination方法，并返回了数据，怎么进行区分开？
// table1
const {data, current, pageSize, total, run} = usePagination(getTable1Data,{
  formatResult: res => res.data.records,
})
// table2
const {data, current, pageSize, total, run} = usePagination(getTable2Data,{
  formatResult: res => res.data.records,
})

能够吧这部分返回内容
const {data, current, pageSize, total, run} 
在放入一个对象中吗？
如：const table1Page = {data, current, pageSize, total, run} ,
使用时，通过
table1Page.data
table1Page .current
进行调用

具体应该怎么写呢？谢谢提供帮助的大佬！

**Comment by aimergenge** [comment]
> 在放入一个对象中吗？

这样当然是可以的。
其实本质上这只是个命名冲突问题。
你可以把多个列表拆分到多个组件里，这样就隔离开了。

**Comment by John60676** [comment]
赋值时不要解构就可以了

```js
const table1Page = usePagination(getTable1Data);
const table2Page = usePagination(getTable2Data);

// ...
table1Page.data;
table2Page.data;

```

**Comment by heishuang** [comment]
> 赋值时不要解构就可以了
> 
> ```js
> const table1Page = usePagination(getTable1Data);
> const table2Page = usePagination(getTable2Data);
> 
> // ...
> table1Page.data;
> table2Page.data;
> ```

非常感谢！这样可以解决我的问题。
