### ISSUE TITLE
[Need Help] Union type can't be handled correctly

### ISSUE THREAD

**Issue by aimergenge** [AttoJS/vue-request#105]
### 问题描述 Problem Description

```ts
const type: 'a' | 'b' = 'a'
const serviceMap = {
  a: serviceA,
  b: serviceB,
}
const { data } = useRequest(serviceMap[type])
```

In this case, the result type of `data` is serviceA's response type, serviceB is just ignored.
I want to know whether this is a problem of vuerequest or this is a problem of typescript itself.

And I want to know if there is any workaround for this.

The expected result type is:
```
const data: responseTypeA | responseTypeB
```

**Comment by John60676** [comment]
`type` is already a definite type, so there is no union type.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/21698973/155057363-38a38f14-5532-4cf6-aa99-75e3777dda5d.png">

**Comment by aimergenge** [comment]
my fault...
```
const type = 'a' as 'a' | 'b'
```

**Comment by aimergenge** [comment]
sorry, it seems it's a question about typescript it self.
