### ISSUE TITLE
是否可以将vue-request用在taro vue3版本

### ISSUE THREAD

**Issue by zjsxfly** [AttoJS/vue-request#106]
看到开发依赖库中加了axios，在taro中使用taro-request请求库，可以支持h5和各平台小程序，vue-request应该脱离于具体http请求库，因为只需要请求的Promise方法，请问是否支持，在实战是否可以被使用。

**Comment by John60676** [comment]
2.x 理论上没有问题，我后续写个点兼容代码应该可以实现

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
