### ISSUE TITLE
Vue3中想建立一个公共方法文件，引用时通过Util.fun1()这种方式调用，应该怎么写？

### ISSUE THREAD

**Issue by heishuang** [AttoJS/vue-request#108]
Vue3中想建立一个公共方法文件Util.js，
引用时import {Util} from './util.js'
通过Util.fun1()这种方式调用，应该怎么写Util.js呢？

**Comment by John60676** [comment]
你这不属于 vue-request 的问题，这种问题麻烦移步其他论坛去提问。

```js
export const Util = {
    fun1(){}
}

```
