### ISSUE TITLE
[Need Help] 使用useLoadMore时碰到的传参问题

### ISSUE THREAD

**Issue by yhf1414104530** [AttoJS/vue-request#109]
### 问题描述 Problem Description

在不使用defaultParams的情况下，直接使用run进行传参数。这个时候使用refresh或者loadMore，请求参数没做保留。
请问怎么解决这个问题。（第一次写vue 就选择了大佬的hook请求库 小白还有很多不明白的）

**Comment by John60676** [comment]
参考 #101 这个 issue

**Comment by yhf1414104530** [comment]
我使用useLoadMore 没有changeCurrent函数。我希望我分页的时候可以携带之前已有的参数

**Comment by John60676** [comment]
看最后两个回复

**Comment by yhf1414104530** [comment]
可是我直接使用run的时候 dataList旧的数据依旧会被保留。就造成了重复数据。
<img width="748" alt="image" src="https://user-images.githubusercontent.com/19488692/156683798-bc969535-0b07-48e8-a9f7-73639f1c5757.png">

**Comment by John60676** [comment]
没太懂你的意思，你说清楚一点你需要达到什么效果

**Comment by yhf1414104530** [comment]
1，添加新的筛选条件进行页面刷新（现在我为了增加参数，刷新的时候直接使用了run，导致旧的数据源也被保留了）
2，在loadMore的时候保留旧的params。

**Comment by John60676** [comment]
可以参考以下代码实现， `reset` 可以在 `useLoadMore` 里面解构出来，文档没有记录的一个方法，可以用来清空 `data`
```js
const refresh = async newParams => {
  const [, ...restParams] = params.value;
  reset(); 
  const mergerParams = [undefined, { ...restParams, ...newParams }];
  await run(...mergerParams);
};
```

**Comment by yhf1414104530** [comment]
可是reset会重新执行一次网络请求，那加上run 就会存在二次请求。

**Comment by John60676** [comment]
`reset` 怎么会重新请求呢，你自己检查一下代码，其他地方触发的

**Comment by yhf1414104530** [comment]
好的 谢谢 你的回答。
