### ISSUE TITLE
[Bug Report]ant design vue 分页demo报错

### ISSUE THREAD

**Issue by bingqingwu** [AttoJS/vue-request#115]
### Bug 描述 Bug description
![image](https://user-images.githubusercontent.com/10008837/159112402-6d0fdd61-e1d5-4920-9ef1-016228edacb9.png)
VueRequest 官网提供的例子直接报错了。
"ant-design-vue": "^2.2.8",
"vue": "^3.2.13",
"vue-request": "^1.2.4",
"typescript": "~4.5.5"

**Comment by John60676** [comment]
那个只是类型报错而已，改成这样就可以了。等我有空再去 antdv 那边改一下 demo 就可以了
```tsx
usePagination<APIResult, [APIParams], APIResult['results']>(xxxx)
```
