### ISSUE TITLE
设置了 throttleInterval，接口返回结果一直为 null

### ISSUE THREAD

**Issue by Zian502** [AttoJS/vue-request#116]
### Bug 描述 Bug description

设置了 throttleInterval，接口返回结果一直为 null

### 期望结果 Desired result

接收到接口返回数据

**Comment by John60676** [comment]
是否自己使用了 `run().then` 去获取数据？

**Comment by John60676** [comment]
2.0 版本的 `debounce` 和 `throttle` 将不会再返回 `null`

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
