### ISSUE TITLE
[Feature Request] 捕获错误默认输出至控制台能否关闭或者由开发者自主控制？

### ISSUE THREAD

**Issue by Ryongyon** [AttoJS/vue-request#117]
### 需求描述 Feature Description
[![qm3NKs.png](https://s1.ax1x.com/2022/03/21/qm3NKs.png)](https://imgtu.com/i/qm3NKs)

尽管可以配置在打包后去除项目中的所有的 console，但是对于强迫症而言希望在开发环境中也能够保持一个干净的控制台

### 建议的解决方案 Proposed Solution
将此函代码去除，或者提供一个配置选项由开发者自行选择是否开启输出错误至控制台

**Comment by John60676** [comment]
2.0 版本将会移除这个 `console.error`

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
