### ISSUE TITLE
[Feature Request] 让loading动画结束的不那么突兀

### ISSUE THREAD

**Issue by DarknessChaser** [AttoJS/vue-request#118]
### 需求描述 Feature Description

让loading动画结束的不那么突兀

### 建议的解决方案 Proposed Solution

现有方案
https://www.attojs.com/guide/documentation/loadingDelay.html
在某个事件后再开始转

建议方案
可以考虑一个至少转一圈的方案。指定一个间隔时间去检查是否loading完成，没到检查时间就算已经完成了也还是loading。这样配合动画持续时间，结束时就不会很突兀。

**Comment by John60676** [comment]
这个需求我要考虑一下

**Comment by DarknessChaser** [comment]
可以搞成可选模式，按需使用嘛

**Comment by John60676** [comment]
> 看文档已经加上这个功能了，但是并没有生效？

他要的效果不是当前版本的效果

**Comment by John60676** [comment]
2.0.0-rc.2 已支持

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
