### ISSUE TITLE
[Feature Request] useLoadMore 考虑加一个 initialDataList 吗

### ISSUE THREAD

**Issue by yeyan1996** [AttoJS/vue-request#119]
### 需求描述 Feature Description
使用 useLoadMore 定义 initialData，只能体现在 data 上，无法设置 dataList 的初始值

**Comment by John60676** [comment]
我考虑一下，`useLoadMore` 还在考虑如何重构

**Comment by yeyan1996** [comment]
还有一个功能点希望可以考虑一下，能否开放自定义 dataList 的合并逻辑（现在是简单的 concat?），这对于需要部分合并分页数据的需求很有用

**Comment by yeyan1996** [comment]
另外就是能使用 mutate 或者其他 api 修改 dataList 么？

**Comment by John60676** [comment]
v2 中，`useLoadMore` 可以使用 `mutate` 修改 `data` 了。
至于其它问题，由于 `dataList` 只是内部做了一个 computed 去取，`data.list` 如果需要其他逻辑，可以不用内置的 `dataList`，直接通过 `data` 去构造自己想要的结果即可。

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
