### ISSUE TITLE
文档能不能写几个例子啊

### ISSUE THREAD

**Issue by whsame** [AttoJS/vue-request#122]
看文档都是些API,不会用.   希望文档写几个例子结合pinia  axios

**Comment by John60676** [comment]
文档已经提供了常用的 API 的例子了 https://www.attojs.com/guide/introduction.html

**Comment by whsame** [comment]
11行打印如下&nbsp; &nbsp;我再写console.log(data.value) 可是为undefined . 我想分别获取数据里面的 id title author 怎么写呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AttoJS/vue-request"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AttoJS/vue-request] 文档能不能写几个例子啊 (Issue #122)





 
文档已经提供了常用的 API 的例子了 https://www.attojs.com/guide/introduction.html

**Comment by John60676** [comment]
ref #32
