### ISSUE TITLE
关于返回结果的疑问

### ISSUE THREAD

**Issue by guohui666** [AttoJS/vue-request#127]
### 问题描述 Problem Description
刚刚尝试使用`vue-request@next`，发现返回的结果是一个联合类型，没法进行解构，有没有什么方式能正常解构结果而不报错吗？
```javascript
export const getClientDetail = (params: {
  clientId: number | null
}) => request.get<{
  client: Record<string, any>
  contracts: any[]
  tax: {
    serviceTaxStatus: number
  }
}>('/wb/getClient', params)

```

```javascript
const { runAsync, data } = useRequest(getClientDetail, {
  defaultParams:[{
    clientId: props.clientId
  }],
  manual: true
})

runAsync({
  clientId: props.clientId
}).then((res)=>{
  res?.data.client
  const {data} = res
})
```
![image](https://user-images.githubusercontent.com/32350854/165667633-ab0e8d2f-0550-474f-bd80-5c7ad7298bf4.png)

**Comment by John60676** [comment]
因为 `res` 有可能是 `void`，前面加个 if 判断一下就可以了

**Comment by guohui666** [comment]
> 因为 `res` 有可能是 `void`，前面加个 if 判断一下就可以了

这样确实可以，但是直接解构的这种怎么弄😂
```javascript
runAsync({
  clientId: props.clientId
}).then(({ data })=>{
    data.client
  // res?.data.client
  // if (res){
  //   const {data} = res
  // }
})
```
![image](https://user-images.githubusercontent.com/32350854/165669137-15f8f70d-2e10-481d-a921-3844623a6ddb.png)

**Comment by John60676** [comment]
没有办法哦，只能是先判断一下再进行解构了

**Comment by guohui666** [comment]
> 没有办法哦，只能是先判断一下再进行解构了

只能这样了，先这么写吧。按我的理解，都正确执行then了，返回类型是不是就直接使用自己提供的返回类型就好了

多写一步，😫难受啊

**Comment by John60676** [comment]
下个版本改进一下

**Comment by guohui666** [comment]
> 下个版本改进一下

等待大佬的改进

fork源码看了下，在处理一些中断请求的情况时确实会返回null，思考了下这种情况如果由一个中断请求的回调来处理的同时不返回结果，一直处于padding状态的runAsync会不会没法被回收掉？

**Comment by John60676** [comment]
只要不引用，就会被回收掉

**Comment by John60676** [comment]
修复了，这两天会更新一个版本

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
