### ISSUE TITLE
[Need Help]useRequest返回值data是一个RefImpl对象，如何访问到接口返回值

### ISSUE THREAD

**Issue by qq2627767202** [AttoJS/vue-request#130]
### 问题描述 Problem Description

今天在用vue-request时，发现useRequest返回值data是一个RefImpl对象，不能直接处理返回值，需要写在template里面才能看见，查了google说可以.value获取，但是我这边.value获取到的是一个undefined，所以如何获取接口返回值呢，肯定是要做处理的。

### 其他信息 Other information
![image](https://user-images.githubusercontent.com/31646567/169447314-949f99d0-cf53-4399-8884-f06d1a7ed88a.png)

**Comment by John60676** [comment]
因为请求是异步的，你第14行的代码是同步代码。
如果你要对数据进行 格式化 等处理的，可以在 computed 里面去处理。
如果你是要在某个 事件/方法 里使用的，直接使用即可。

**Comment by qq2627767202** [comment]
懂了，蟹蟹，一时半会没反应过来
