### ISSUE TITLE
antdv 分页配置

### ISSUE THREAD

**Issue by fc88804DOTcn** [AttoJS/vue-request#131]
### 问题描述 Problem Description
在使用 usePagination 方法是如何配置pages、total等字段映射。

在使用antdv table 的加载远程数据时推荐用到 vue-request 插件，想着可以自动控制加载状态和分页操作也挺好的。但是配置加载完数据之后分页信息配置不上  我百度了很久 也尝试做了一些配置 ，实在是没找到怎么配置totls和pages等信息的方法。无奈 来到这里寻求帮互助 先行答谢有缘人了

[antdv 例子：](https://www.antdv.com/components/table-cn#components-table-demo-ajax)

### 其他信息 Other information
``` javascript
import { usePagination } from "vue-request";
import _api from "@http/api";
import {
  computed,
  defineComponent,
  onBeforeUnmount,
  onMounted,
  reactive,
  ref,
  watch,
  inject,
} from "vue";
import { useStore } from "vuex";
import { useRouter, useRoute } from "vue-router";
export default {
  name: "menu-bs",
  setup(props, context) {
    const store = useStore();
    const router = useRouter();

    const columns = [
      {
        title: "Name",
        dataIndex: "name",
        sorter: true,
        width: "20%",
      },
      {
        title: "Gender",
        dataIndex: "gender",
        filters: [
          {
            text: "Male",
            value: "male",
          },
          {
            text: "Female",
            value: "female",
          },
        ],
        width: "20%",
      },
      {
        title: "Email",
        dataIndex: "email",
      },
    ];

    const queryPageData = _api.menuApiModules.page;

    const {
      data: dataSource,
      run,
      loading,
      total,
      current,
      pageSize,
    } = usePagination(queryPageData, {
      formatResult: (res) => {
        return res.data.data.records
      },
      pagination: {
        currentKey: "pageNum",
        pageSizeKey: "pageSize",
        totalKey: "res.data.data.total"
      },
    });


    const pagination = computed(() => ({
      total: total.value,
      current: current.value,
      pageSize: pageSize.value,
      hideOnSinglePage: true,
    }));

    const handleTableChange = (pag, filters, sorter) => {
      run({
        results: pag.pageSize,
        page: pag?.current,
        sortField: sorter.field,
        sortOrder: sorter.order,
        ...filters,
      });
    };

    return {
      dataSource,
      pagination,
      loading,
      columns,
      handleTableChange,
    };
  },
};
```

我的数据是这样的
``` json
{
  "code": 200,
  "data": {
    "records": [
      {
       ```数据对象```
      },
    ],
    "total": 12,
    "size": 10,
    "current": 1,
    "orders": [],
    "optimizeCountSql": true,
    "searchCount": true,
    "countId": null,
    "maxLimit": null,
    "pages": 2
  },
  "msg": "菜单数据分页查询成功"
}
```
vue devtools 截图
![image](https://user-images.githubusercontent.com/59227215/170969271-ce3e1b05-93f0-47a6-a580-599396bdf7db.png)

**Comment by John60676** [comment]
`total` 会取 `formatResult` 之后的结果

**Comment by fc88804DOTcn** [comment]
> `total` 会取 `formatResult` 之后的结果。 推荐你直接用 2.x 版本，迁移手册在这里 #121

好的 我装了2.X beta版本，但是sql忘记git了 明天试一下。
还有就是 您说的 “total 会取 formatResult 之后的结果” 意思是  total值会取 formatResult 对象 total 的值吗？
可是1.x版本 formatResult 是个数组啊。是不是在2版本中 把total、pages值赋值给 formatResult 对象就可以啦？

**Comment by fc88804DOTcn** [comment]
@John60676 抱歉，说实话，我还是不知道怎么配置啊 能不能给我看一下case 啊

**Comment by John60676** [comment]
> 还有就是 您说的 “total 会取 formatResult 之后的结果” 意思是 total值会取 formatResult 对象 total 的值吗？

是的

> 可是1.x版本 formatResult 是个数组啊。是不是在2版本中 把total、pages值赋值给 formatResult 对象就可以啦？
formatResult 结果是什么，取决于你返回的值是什么

```js
const {
  data: dataSource,
  run,
  loading,
  total,
  current,
  pageSize,
} = usePagination(queryPageData, {
  formatResult: res => {
    // 返回包含 records 和 total 的对象
    return res.data.data;
  },
  pagination: {
    currentKey: "pageNum",
    pageSizeKey: "pageSize",
    // totalKey 其实就是取 data 里面的total 的路径值
    totalKey: "total",
  },
});
```

**Comment by fc88804DOTcn** [comment]
@John60676 改成上述代码之后，foramResult 中，useLazyKeyMvn.js > dig 方法不过(前面几次records空，第三次时为返回的包含(records、totla等字段)的Proxy对象，但是dig方法会使用foreach遍历对象本身，提示对象没有foreach方法)。
``` javascript
import _typeof from "@babel/runtime/helpers/esm/typeof";
import { watch, shallowRef } from 'vue';
export default function useLazyKVMap(dataRef, childrenColumnNameRef, getRowKeyRef) {
  var mapCacheRef = shallowRef({});
  watch([dataRef, childrenColumnNameRef, getRowKeyRef], function () {
    var kvMap = new Map();
    var getRowKey = getRowKeyRef.value;
    var childrenColumnName = childrenColumnNameRef.value;
    /* eslint-disable no-inner-declarations */

    function dig(records) {
      records.forEach(function (record, index) {
        var rowKey = getRowKey(record, index);
        kvMap.set(rowKey, record);

        if (record && _typeof(record) === 'object' && childrenColumnName in record) {
          dig(record[childrenColumnName] || []);
        }
      });
    }
    /* eslint-enable */


    dig(dataRef.value);
    mapCacheRef.value = {
      kvMap: kvMap
    };
  }, {
    deep: true,
    immediate: true
  });

  function getRecordByKey(key) {
    return mapCacheRef.value.kvMap.get(key);
  }

  return [getRecordByKey];
}
```
![image](https://user-images.githubusercontent.com/59227215/171087240-62a45056-228b-4c36-b713-d127f08b4faf.png)
![image](https://user-images.githubusercontent.com/59227215/171087593-9f4a7dc0-308c-4efd-a10c-80715d0d42f2.png)

**Comment by John60676** [comment]
你的 `dataRef.value` 是一个对象啊，不是一个数组，你要遍历的数组在 `dataRef.value.records` 里面。
你可以先看看文档里面， `formatResult` 这个 API 的用法 https://www.attojs.com/api/#formatresult

**Comment by fc88804DOTcn** [comment]
嗯嗯 看啦，但是我没有遍历他，是那个useLazyKVMap.js这个去遍历的这个对象

**Comment by John60676** [comment]
> @John60676 嗯嗯 看啦，但是我没有遍历他，是那个useLazyKVMap.js这个去遍历的这个对象。这段代码不是我调用的

那这也跟 vue-request 没关系，你别把 `data` 直接传进去就好了，你传个 `data.value.records`

**Comment by fc88804DOTcn** [comment]
![01169E5A](https://user-images.githubusercontent.com/59227215/171101019-10694420-8cf3-469d-8c19-075e5a14c796.png)
那我的理解能力好差啊  ，就是有一个我改变不了的dig(formatResult)方法，会把formatResult当做数组处理，然后不传数组他报错，传了数组我不知道怎么挂载total属性![01169E5A](https://user-images.githubusercontent.com/59227215/171101019-10694420-8cf3-469d-8c19-075e5a14c796.png)![01169E5A](https://user-images.githubusercontent.com/59227215/171101019-10694420-8cf3-469d-8c19-075e5a14c796.png)![01169E5A](https://user-images.githubusercontent.com/59227215/171101019-10694420-8cf3-469d-8c19-075e5a14c796.png) @John60676

**Comment by John60676** [comment]
你不要用 `formatResult` 就好了啊

```js
const { data, run, loading, total, current, pageSize } = usePagination(
  queryPageData,
  {
    // formatResult: res => {
    //   return res.data.data.records;
    // },
    pagination: {
      currentKey: "pageNum",
      pageSizeKey: "pageSize",
      totalKey: "res.data.data.total",
    },
  }
);

const dataSource = computed(() => res.data.data.records);
```

**Comment by fc88804DOTcn** [comment]
@John60676 十分感谢您。我太愚笨了是，怎么做还是没映射到total，暂时先搁置一下。谢谢您啦 
![0152A358](https://user-images.githubusercontent.com/59227215/171109893-8f6ff942-82af-4362-a8b4-96e79709ca0b.png)

**Comment by fc88804DOTcn** [comment]
@John60676 十分感谢您。我太愚笨了是，怎么做还是没映射到total，暂时先搁置一下。谢谢您啦 
![0152A358](https://user-images.githubusercontent.com/59227215/171109893-8f6ff942-82af-4362-a8b4-96e79709ca0b.png)

**Comment by sushuier** [comment]
我也没理解，usePagination返回的total是从哪来的；antdv中的实例，传入的service方法只返回了数组，并没有返回total；那么usePagination是如何准确的获取total呢；

**Comment by fc88804DOTcn** [comment]
你好，我回头翻看了下我当时的提问现在的视角是认为：
1、首先vue-request是一个插件，在处理分页请求的时候有一套自己的逻辑
2、插件逻辑和对接的server端不会都能无缝对接很一致，在处理这些不一致的时候分两种情况，
a)&nbsp;一种是直接告诉插件你要的A字段值实际上在我这里的名字叫B字段，我把转换关系告诉你你自己去取就行
b)&nbsp;通过formResult自行处理，最终构建出来一个可以让插件使用的分页数据对象，相当于一种formatter一样的处理函数，在这个函数体内，开发者自己按照实际情况构建数据对象，total，data等自己配置挂载。


详细的东西，我想大概是打开源码看一下就明白了。





                    ***@***.***&gt;&nbsp;在 2026年7月24日 周五 14:08 写道：

sushuier left a comment (AttoJS/vue-request#131)
 
我也没理解，usePagination返回的total是从哪来的；antdv中的实例，传入的service方法只返回了数组，并没有返回total；那么usePagination是如何准确的获取total呢；
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
