### ISSUE TITLE
[Need Help] run 进行主动请求时没有走缓存

### ISSUE THREAD

**Issue by yuntian001** [AttoJS/vue-request#133]
### 问题描述 Problem Description

为什么 run 进行主动请求时没有走缓存，希望run 调用请求的时候也可以走缓存

**Comment by John60676** [comment]
没有走缓存是指？

**Comment by yuntian001** [comment]
> 没有走缓存是指？
我设置了 caheKey 和 staleTime 然后用run 发起起请求， 第二次请求依然进行了真正的请求，并没有从缓存中取值。

**Comment by yuntian001** [comment]
> 没有走缓存是指？

我设置了 caheKey 和 staleTime 然后用run 发起起请求， 第二次请求依然进行了真正的请求，并没有从缓存中取值。

**Comment by John60676** [comment]
可以给个重现示例吗

**Comment by yuntian001** [comment]
```
<script setup>
import { useRequest } from 'vue-request';
import axios from 'axios';

const getUser = userName => {
  return axios.get('http://jsonplaceholder.typicode.com/posts');
};

const { data, run } = useRequest(getUser, {
  cacheKey: 'test'
  , staleTime: 60000
});

// ...
let api = () => {
  run();
}
</script>

<template>
  <button @click="api()">请求</button>
</template>

<style>
</style>

</script>

<template>
  <button @click="api()">请求</button>
</template>

<style>

</style>

```

每点击一次请求 就会发起一次真正的请求
但是我看保鲜时间 的文档介绍 -在保鲜时间内应该是直接返回之前的结果不发起新请求

保鲜时间
如果你能确保缓存下来的数据，在一定时间内不会有任何更新的，你可以设置一个保鲜时间 [staleTime](https://cn.attojs.org/api/index.html#staletime) （默认为 0，即不保鲜）, 当设置保鲜时间后，VueRequest 在该时间内会认为缓存的数据是新鲜的，从而不会发起新的请求，这能为一些定时更新的接口减轻请求的压力。

**Comment by yuntian001** [comment]
刚试了下 v2没有这个问题 V1有这个问题

**Comment by John60676** [comment]
v1 是这样设计的，并不是 bug

**Comment by yuntian001** [comment]
@John60676 这就尴尬了，V2啥时候发版正式版。

**Comment by John60676** [comment]
现在用也没啥大问题，主要功能都做完了
