### ISSUE TITLE
请教如何重置初始状态

### ISSUE THREAD

**Issue by jukanntenn** [AttoJS/vue-request#139]
考虑这样一个场景：用户点击弹出模态框时，发起请求；关闭模态框后，重置 data, error 等为初始状态，这样下次用户再点击弹出模态框时，不会残留上一次的结果。目前我的做法是这样的：

```javascript
{data, error, loading, run, mutate} = useRequest(service, {initialData: []})

// 模态框弹出
run()

// 模态框关闭
data.value = []
error.value = undefined
```

不知道这样做是否有什么副作用。

另外我发现，如果我用 `mutate([])` 来重置 `data`，控制台打印 data 的值是 `{}`，而不是 `[]`，似乎和预期的行为不符。

**Comment by John60676** [comment]
`mutate([])` 的结果确实是不正确

**Comment by John60676** [comment]
fixed in rc.3
