### ISSUE TITLE
Cached data not loaded

### ISSUE THREAD

**Issue by alih70442** [AttoJS/vue-request#140]
### 问题描述 Problem Description

Hi,
in a view, I have one component that I should render twice,
In this component I use useRequest with cacheKey.
first component make request and has data.
but second request doesn't make any request and doesn't have any data.
they are one component with one cacheKey.
what's happening?

### 其他信息 Other information

This is the useRequest code:
![image](https://user-images.githubusercontent.com/57169848/178098607-b39b1d87-70d7-4b3a-9e5a-c9879da174f3.png)

**Comment by alih70442** [comment]
If I remove ```staleTime```, second component make request too.
so it will have data.
but it is abnormal to make second request for same data.

**Comment by John60676** [comment]
I can't reproduce your problem.

https://codesandbox.io/s/wonderful-spence-3h76eh?file=/src/components/HelloWorld.vue

**Comment by alih70442** [comment]
My vue-request version is ```"vue-request": "^1.2.4"```
This bug has fixed at version 2.
please update npm install version to 2.0.0
Thanks for this great library.
Wish I could contribute.

**Comment by John60676** [comment]
There are still some features to be done at the moment, when these are completed, I will release the 2.0 version.
