### ISSUE TITLE
[Need Help]vue2 compositionAPi 会报错

### ISSUE THREAD

**Issue by zhangjun620** [AttoJS/vue-request#142]
### 问题描述 Problem Description

我的环境是vue2.6 ， 装了 vue-compositionApi的npm包
运行时会报错，是因为我在 setup script 标签写的原因吗，我尝试了下在vue2 option api写法也会报这个错
### 其他信息 Other information

![image](https://user-images.githubusercontent.com/24204540/178636042-2b538b54-f653-42bd-9d41-59470861dae1.png)
![image](https://user-images.githubusercontent.com/24204540/178636073-e632db91-6ddf-4f64-9593-a26588864623.png)
![image](https://user-images.githubusercontent.com/24204540/178636277-13e9deee-1012-4085-9d8e-4e4bd6231158.png)

**Comment by John60676** [comment]
打印一下 vue 的版本，确认一下是否装的是 2.6.x

**Comment by zhangjun620** [comment]
不好意思，我看了下是 2.5.10，我现在的这个版本支持吗？  我下个项目可以升级 2.7的版本

**Comment by John60676** [comment]
`vue-demi` 支持的话，都是可以的。同时还要确保 `vue-request` 的版本是 2.x
