### ISSUE TITLE
[Need Help]vue3.2.36 使用options API写的。会有警告。

### ISSUE THREAD

**Issue by zrad** [AttoJS/vue-request#144]
### 问题描述 Problem Description

虽然用的vue3，vueRequest是rc-3，但是写法是options API写法。然后使用时，控制台会报警告。
### 其他信息 Other information

![image](https://user-images.githubusercontent.com/15223877/179439251-6cc53e2c-92f9-4c83-ad54-403a19b402c2.png)
![image](https://user-images.githubusercontent.com/15223877/179439292-ba130408-6b32-492a-952f-d61c708d8329.png)
![image](https://user-images.githubusercontent.com/15223877/179439301-c91c22b7-dd4b-40a4-9fb5-e19aff8e696d.png)

**Comment by John60676** [comment]
只能用在 `setup` 里面

**Comment by zrad** [comment]
噢。好吧。那很限制使用条件。等于说不能 vue3 optionsAPI混写了。那vue2怎么兼容的呢、？

**Comment by John60676** [comment]
这不是我们限制的，Vue 3 的 composition-api 本身就有这个要求。Vue 2 也是要写在 setup 里面。
- Vue < 2.7 的要自行引入 `@vue/composition-api`
- Vue >= 2.7 的直接像 Vue 3 一样写
