### ISSUE TITLE
官网有问题。。。。

### ISSUE THREAD

**Issue by xu-Aurora** [AttoJS/vue-request#145]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/35291465/179466876-60a8e00d-b815-4160-bab6-5ecc72153b29.png">

**Comment by John60676** [comment]
我这边看没问题，你换到国内源吧
![image](https://user-images.githubusercontent.com/21698973/179467621-49c2e292-7147-4bf0-b430-0d744eb53be3.png)

**Comment by xu-Aurora** [comment]
> 我这边看没问题，你换到国内源吧 ![image](https://user-images.githubusercontent.com/21698973/179467621-49c2e292-7147-4bf0-b430-0d744eb53be3.png)

1. 怎么切，没有看到切的按钮啊
2. 我就是开着vpn的

**Comment by John60676** [comment]
https://www.attojs.com

**Comment by xu-Aurora** [comment]
> https://www.attojs.com

我访问的就是这个地址有问题

**Comment by xu-Aurora** [comment]
> https://www.attojs.com



我访问的就是这个地址有问题

**Comment by John60676** [comment]
自行检查一下是不是有什么扩展禁用了 pwa 的更新。换个浏览器或者开启无痕模式。你这个很久没更新了。可以对比一下我截图右下角的更新时间

**Comment by xu-Aurora** [comment]
> https://www.attojs.com

好的，换了浏览器确实可以了，估计是chrome浏览器上面插件影响了，我自己排查下吧。谢谢
