### ISSUE TITLE
[Need Help] Webstorm还是有类型错误提示

### ISSUE THREAD

**Issue by winter-ice** [AttoJS/vue-request#146]
### 问题描述 Problem Description

(https://github.com/AttoJS/vue-request/issues/121#issuecomment-1085303921)

### 其他信息 Other information
OS: MacOs 12.4
IDE: 全新安装的 WebStorm 2022.1.3
version: 2.0.0-rc.3

**Comment by John60676** [comment]
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/21698973/179679887-89f73afe-c622-4332-8863-16ad5a562e8e.png">


还是像上次一样，我这边均无法重现。

测试环境是 vite 新创建的。

你要不提供一个可重现的示例？

**Comment by winter-ice** [comment]
Webstorm 官网新下的，项目是Vite新建的
<img width="621" alt="image" src="https://user-images.githubusercontent.com/24680921/179681260-400d21d5-7f4f-4268-b243-d37b12ca2fe2.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/24680921/179681297-dcbaa7de-76ea-42cf-b8af-d1162643033a.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/24680921/179681323-cf26004f-8b49-4f68-8e8d-9773d423258d.png">

**Comment by winter-ice** [comment]
问题出在script不指定lang=ts

**Comment by John60676** [comment]
如果你要有类型支持，请加上 `lang="ts"`
