### ISSUE TITLE
[Need Help] v2版本 在组件外调用，比如初始化之前会报警告 inject() can only be used inside setup()，onUnmounted is called when there is no active component instance to be associated with.

### ISSUE THREAD

**Issue by yuntian001** [AttoJS/vue-request#149]
### 问题描述 Problem Description
v2版本 在组件外调用，比如初始化之前会报警告 inject() can only be used inside setup()，onUnmounted is called when there is no active component instance to be associated with.

能不能加个判断把这个警告去掉
### 其他信息 Other information

![image](https://user-images.githubusercontent.com/43692243/180691932-5093844a-a81d-400c-bd30-fcde6c017cdf.png)

**Comment by John60676** [comment]
首先，这是 Vue 的警告。其次，我们也不建议在 setup 外去使用

**Comment by yuntian001** [comment]
> 首先，这是 Vue 的警告。其次，我们也不建议在 setup 外去使用

去请求权限信息和路由信息然后动态添加有权限的路由，必须要在渲染之前调用啊。

**Comment by John60676** [comment]
你是想说在路由的导航守卫去用是吧？

我们不太建议路由导航用 useRequest，因为那里也不需要用到响应式，直接用 axios 就可以了

**Comment by yuntian001** [comment]
onUnmounted做了哪些操作,有没有可能通过参数设置去规避这个问题。
这个接口我已经设置manual 手动触发了，感觉应该用不到onUnmounted

**Comment by John60676** [comment]
内部用来做状态、订阅管理等处理，具体可以翻看 2.x 的源码。

还是那句，setup 外没有使用 useRequest 的必要。

**Comment by zrad** [comment]
那语法糖 <script setup>也报这个错误是为什么呢？

**Comment by John60676** [comment]
> 那语法糖 <script setup>也报这个错误是为什么呢？

提供个示例，我这边没有报错

**Comment by zrad** [comment]
![image](https://user-images.githubusercontent.com/15223877/219286967-cf4e922d-6121-4e96-9bd2-66ceb65b63ee.png)
![image](https://user-images.githubusercontent.com/15223877/219287520-23568e85-f3e4-4dfb-af34-bee0f6c330e3.png)
![image](https://user-images.githubusercontent.com/15223877/219287660-a50229bb-572b-4a9f-b35f-50fbf88ee6d1.png)
大概代码片段是这样的。父组件直接xxxref.value.updateTerminalValue调用图1中的函数。就会出现跟题主一样的警告。
@John60676

**Comment by liuyunhaha** [comment]
那语法糖 <script setup>也报这个错误是为什么呢？

`<script setup lang="ts" name="Index">
import { getStuDetailInfo, updateIdcardUrl } from '@/api/user'

useRequest(getStuDetailInfo, {
  onBefore: () => {
    uiUtils.loading()
  },
  onSuccess: (res: any) => {
    userInfo.value = res.data
    cache.local.setJSON('userInfo', userInfo.value)
    uiUtils.closeToast()
  }
})
</script>`
