### ISSUE TITLE
[Need Help]返回的data类型是RefImpl，拿不到value的内容

### ISSUE THREAD

**Issue by lk-yu** [AttoJS/vue-request#150]
![b](https://user-images.githubusercontent.com/57137725/181663112-400408ce-97ad-4d7e-9a6b-dc1612c9d387.jpg)

**Comment by John60676** [comment]
#130

**Comment by lk-yu** [comment]
@John60676 是这种方式来异步等待进行response的业务处理，没有别的方法了吧，感谢提示！
![c](https://user-images.githubusercontent.com/57137725/181667379-aa050943-9a42-4261-af2c-d5ecc413a07f.png)

**Comment by John60676** [comment]
`computed`、`watch` 都可以拿到

**Comment by lk-yu** [comment]
好的感谢
