### ISSUE TITLE
[Bug Report] 服务端渲染时，存在内存泄漏

### ISSUE THREAD

**Issue by yeyan1996** [AttoJS/vue-request#153]
### Bug 描述 Bug description
1.2.4 版本，使用 useLoadMore 在服务端运行时，会有内存泄漏

### 代码重现 Reproduce
https://github1s.com/AttoJS/vue-request/blob/HEAD/src/core/utils/listener.ts#L9
https://github1s.com/AttoJS/vue-request/blob/HEAD/src/core/useAsyncQuery.ts#L242

### 其他信息 Other information

![image](https://user-images.githubusercontent.com/39046570/182588968-1deda57a-9fa5-4800-9216-b858aaaebf45.png)

![image](https://user-images.githubusercontent.com/39046570/182589204-4d8d8553-74e2-42d1-a4d8-af7290801c4f.png)

原因是服务端没有 onUnmount 事件，导致 Set 越加越多

**Comment by John60676** [comment]
close #235
