### ISSUE TITLE
[Feature Request]这个有防重复提交嘛

### ISSUE THREAD

**Issue by wuzesen** [AttoJS/vue-request#162]

**Comment by John60676** [comment]
有的

**Comment by wuzesen** [comment]
哪个配置啊，没看到

**Comment by John60676** [comment]
节流与防抖
https://next.attojs.com/guide/documentation/debounce.html

**Comment by wuzesen** [comment]
防抖与节流没法解决吧
我的期望是点击的时候会发请求,然后请求没有返回,loading的时候不允许重复发送
但是防抖和节流在loading的时候也是可以发送请求的吧

**Comment by wuzesen** [comment]
这个可以做个配置吗,这种场景还是很常见的

**Comment by John60676** [comment]
ready 就是符合这种场景使用了
