### ISSUE TITLE
[Bug Report]mutate传入数组时会被转为对象

### ISSUE THREAD

**Issue by kylee0325** [AttoJS/vue-request#163]
### Bug 描述 Bug description
返回的mutate函数，在传入数组时会被转为对象，原因是isObject方法无法排除Array

源码如下：
const isObject = val => val !== null && typeof val === 'object';

context.mutate = x => {
    const mutateData = isFunction(x) ? x(data.value) : x;

    const _mutateData = isObject(mutateData) ? Object.assign({}, mutateData) : mutateData;

    setState({
      data: _mutateData
    });
    emit('onMutate', _mutateData);
  };

### 代码重现 Reproduce
const { mutate } = useLoadMore(service);

mutate([]);

**Comment by John60676** [comment]
这个问题 rc.3 https://github.com/AttoJS/vue-request/commit/804a69df15217c144175abd2fc31660146475a64 就已经修复了，你检查一下版本

**Comment by kylee0325** [comment]
![image](https://user-images.githubusercontent.com/36921713/190296311-ebf3a762-fc3b-4495-a5ec-2b072228d369.png)
![image](https://user-images.githubusercontent.com/36921713/190296358-097ccf47-60ca-4e83-9fd3-9cbc596812a8.png)
烦请检查一下发版是否正常？我这确实是rc.3  但代码并不是你刚发的新的

**Comment by John60676** [comment]
嗯，确实是发版的失误，rc.4 没问题了
