### ISSUE TITLE
[Need Help]如何停止轮询请求

### ISSUE THREAD

**Issue by zrad** [AttoJS/vue-request#168]
### 问题描述 Problem Description

useRequest(Service,{
pollingInterval:1000,
onSuccess:()=>{
  ????
}
})
怎么在onSuccess里根据逻辑停止再轮询呢??
直接cancel()没有此方法,文档里没太看明白这个取消

**Comment by John60676** [comment]
```js
const { cancel } = useRequest(Service, {
  pollingInterval: 1000,
  onSuccess: () => {
    cancel()
  },
});


```
