### ISSUE TITLE
使用此vue-request使用mockjs

### ISSUE THREAD

**Issue by mrjasonjiang** [AttoJS/vue-request#17]
如题

**Comment by John60676** [comment]
你是想问如何配合 mockjs 使用吗

**Comment by mrjasonjiang** [comment]
是的

**Comment by John60676** [comment]
我们内置是使用 [`Fetch`](https://developer.mozilla.org/zh-CN/docs/Web/API/WindowOrWorkerGlobalScope/fetch) 请求的，`Mock.js` 只支持 [`XMLHttpRequest`](https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest) 的拦截，不支持 `Fetch` 的拦截。所以我们给出的方案是：
 - 可以更换一个支持 `Fetch` 的 Mock 库
 - 封装一个 `XMLHttpRequest` 的请求，或者直接使用 [`axios`](https://github.com/axios/axios) 来请求
 
这里给你一个 `axios`  的 demo 参考一下

https://codesandbox.io/s/young-butterfly-k5yv8?file=/src/App.jsx

**Comment by mrjasonjiang** [comment]
谢谢
