### ISSUE TITLE
[Need Help]为什么vue2.7版本和3.0版本的模板渲染显示不一样

### ISSUE THREAD

**Issue by wuzesen** [AttoJS/vue-request#170]
vue2.7版本
![image](https://user-images.githubusercontent.com/20244141/198531741-b2a970c1-9964-4b85-979e-2943c7a2f931.png)
vue3.x版本
![image](https://user-images.githubusercontent.com/20244141/198532066-320403d6-a9fe-4c21-acc5-8c63b42afd2c.png)

同样的两份代码，为啥3.x版本的可以解构赋值，而2.7版本的不可以

**Comment by John60676** [comment]
提供一下 demo 地址，检查一下 vue-request 的版本是不是 2.x 的

**Comment by wuzesen** [comment]
https://codesandbox.io/s/shou-dong-chu-fa-qing-qiu-shi-li-vue-request-2-0-0-rc-2-forked-40bp41?file=/src/Demo.vue

切换一下vue版本，并且修改main.js里的代码就可以测试了

**Comment by John60676** [comment]
准确来说，这是 vue 的问题

https://codesandbox.io/s/shou-dong-chu-fa-qing-qiu-shi-li-vue-request-2-0-0-rc-2-forked-6clnur?file=/src/Demo.vue

**Comment by wuzesen** [comment]
好的，感谢
