### ISSUE TITLE
[Need Help] currentKey pageSizeKey不能获取到后端返回的值

### ISSUE THREAD

**Issue by gggitpl** [AttoJS/vue-request#178]
接口返回数据类型
![image](https://user-images.githubusercontent.com/9427907/207530510-573488dc-ae03-48dc-9e85-b8712a7d7a01.png)

const { data, loading, current, pageSize, total } = usePagination(() => queryAccount(formState), {
  pagination: {
    currentKey: 'data.number',
    pageSizeKey: 'data.size',
    totalKey: 'data.totalElements',
  },
});

pageSize 始终是10 current 始终是1

**Comment by John60676** [comment]
`pageSizeKey` 指的是你请求接口时传入的分页参数，而不是接口返回的 page size
