### ISSUE TITLE
[docs] Broken link in sidebar in docs

### ISSUE THREAD

**Issue by Kgnx7** [AttoJS/vue-request#181]
### Duplicates
- [x] I have searched the existing issues

### Related page
https://next.attojs.org/guide/documentation/queries.html

### Issue description

In sidebar under "Documentation" section there is a strange link - "/guide/documentation/queries.html"

### Reproduce

Go to any page in docs where the sidebar is visible

### Desired result

All link readable and working

### Context

![image](https://user-images.githubusercontent.com/28836290/214010046-3171bc27-3a74-46ae-8250-ab83243fae32.png)

**Comment by John60676** [comment]
Thanks for the feedback, it has been fixed
