### ISSUE TITLE
[Bug Report] undefined injectedGlobalOptions

### ISSUE THREAD

**Issue by FirstSanny** [AttoJS/vue-request#182]
### Bug 描述 Bug description
In the usePagination function we are running into the problem that `injectedGlobalOptions` are undefined in this line 
```pagination: (_injectedGlobalOption = injectedGlobalOptions.pagination) !== null && _injectedGlobalOption !== void 0 ? _injectedGlobalOption : {}```
When just replacing `injectedGlobalOptions.pagination` with `injectedGlobalOptions?.pagination` it works.

### 代码重现 Reproduce
I honestly dont know how to reproduce it.

### 期望结果 Desired result
No undefined error and breaking the code.

**Comment by LuXDAmore** [comment]
Same for me

![image](https://github.com/AttoJS/vue-request/assets/3841171/71e5f386-2ec4-43b5-88c0-eb617de12eed)

![image](https://github.com/AttoJS/vue-request/assets/3841171/a6543afe-4244-4447-87d1-56c5e6cef85c)

This line is undefined
> const injectedGlobalOptions = vueDemi.inject(GLOBAL_OPTIONS_PROVIDE_KEY, {});
I'm using the same service on every page with the same data, but just in one page is broken with this error.

**Comment by liuhean** [comment]
我出现类似问题，最终发现是各个组件库依赖的vue-demi的版本不一致导致的问题

**Comment by code-lixm** [comment]
我也遇到了类似的问题，出现的情况是没有在正确的inject环境使用，vue-request 应该排除 没有inject的情况时，也能正确使用，比如在一个js文件中使用时
