### ISSUE TITLE
[Need Help]请求返回值添加了null的联合类型导致在typescript中解构结果报错

### ISSUE THREAD

**Issue by MissFlower** [AttoJS/vue-request#186]
### 问题描述 Problem Description
因为run: (...arg: P) => Promise<R | null>返回结果包装成了R|null的联合类型 导致获取结果后无法直接解构

### 其他信息 Other information

![image](https://user-images.githubusercontent.com/22770493/220873033-30bb4d2b-a1df-48cc-a73e-3905bb031cd8.png)
![image](https://user-images.githubusercontent.com/22770493/220873111-ae785b38-ef24-4eee-bab5-3f70712830e0.png)

**Comment by John60676** [comment]
用的是哪个版本的？

**Comment by MissFlower** [comment]
1.2.4

**Comment by John60676** [comment]
可以选择更新到2.x, 新版本改了 data 的类型推导

**Comment by MissFlower** [comment]
> 可以选择更新到2.x, 新版本改了 data 的类型推导

好的, 多谢回答,现在2.x还是rc阶段,先用断言处理了 后续发行release了在重构吧

**Comment by John60676** [comment]
其实这个RC已经算是正式的版本了，只是我想把ssr给弄好了再发正式版本。目前我自己的项目也在用着
