### ISSUE TITLE
[Need Help] 请问run函数每次调用都要传参么?

### ISSUE THREAD

**Issue by alleluya-young** [AttoJS/vue-request#187]
### 问题描述 Problem Description
script里声明一个请求的入参param的ref变量, 调用run之前改变param的值, 执行run函数的时候 请求的入参不会响应式更新么? 代码如图
![image](https://user-images.githubusercontent.com/31433884/223610851-28fba18b-e80f-44d6-ae25-98c7ad63e4ec.png)
我试了下 直接run()的话 请求里就没有入参了, 必须写run(param.value) 才能成功发起请求.
想请教的是 这里调用run必须要重新传一下param 请求才会携带参数么?

**Comment by John60676** [comment]
`defalutParams` 不是响应式的
```js
run({
  key: value,
  ...params.value,
});
```

**Comment by alleluya-young** [comment]
> `defalutParams` 不是响应式的
> 
> ```js
> run({
>   key: value,
>   ...params.value,
> });
> ```

就是每次执行run都要显式的传参么? 我看manual设置为true的时候 直接调用run 也没有请求参数

**Comment by John60676** [comment]
是的，其实run就是帮你执行了一遍请求函数，manual 文档里面的示例也是如此

https://next.attojs.com/guide/documentation/manual.html

**Comment by alleluya-young** [comment]
> 是的，其实run就是帮你执行了一遍请求函数，manual 文档里面的示例也是如此
> 
> https://next.attojs.com/guide/documentation/manual.html

好的, 刚才专门看了下文档 示例没出来 我还有点纳闷来着怎么没示例... 
另外请教一下 return values里的params具体是什么场景下使用? 没明白示例的意思...

**Comment by John60676** [comment]
示例现在应该是正常的，今天迁移了一下文档服务器。

如果你只修改了部分参数，就可以直接在 `run` 里面解构 `params`
```js
run({
  ...params.value,
  key: value,
});
```

**Comment by alleluya-young** [comment]
> 示例现在应该是正常的，今天迁移了一下文档服务器。
> 
> 如果你只修改了部分参数，就可以直接在 `run` 里面解构 `params`
> 
> ```js
> run({
>   ...params.value,
>   key: value,
> });
> ```

好的 估计是迁移重启的时候 正好我在访问, 所以没看到示例. 感谢回复, 希望vue-request越来越好~
