### ISSUE TITLE
vue3+vite+ts项目中没有类型提示问题

### ISSUE THREAD

**Issue by 18949673125** [AttoJS/vue-request#191]
### 问题描述 Problem Description
在vue3+vite+ts项目中使用，一直无法准确提示 对应的模块类型，一直提示vue-request无法解析

### 其他信息 Other information

![image](https://user-images.githubusercontent.com/57660383/226083296-d45e3dab-ca64-4e79-95eb-5bea1d818972.png)
![image](https://user-images.githubusercontent.com/57660383/226083322-786e5a2a-6863-4ea9-bb45-8b9a37057c9a.png)

**Comment by John60676** [comment]
提供个示例仓库
