### ISSUE TITLE
[Need Help]是不支持option API写法吗？

### ISSUE THREAD

**Issue by travelCN** [AttoJS/vue-request#194]
### 问题描述 Problem Description

Options API写法，会报警告。在Composition API里目前没问题。是不支持Options API的写法吗？目前不太清楚该怎么写了。

### 其他信息 Other information

![image](https://user-images.githubusercontent.com/15223877/228409801-89321197-e5ed-4ada-8cb1-1bce4566f887.png)
![image](https://user-images.githubusercontent.com/15223877/228410288-03372907-7de1-4f59-b406-2171f92aadf7.png)

**Comment by Tanimodori** [comment]
可以放在option API的setup块里面。

**Comment by travelCN** [comment]
> 可以放在option API的setup块里面。

好的..我去试试
