### ISSUE TITLE
[Feature Request]在传入initialData时去除data中的undefined类型

### ISSUE THREAD

**Issue by yangmiao7** [AttoJS/vue-request#195]
### 需求描述 Feature Description

目前```useRequest```方法调用时，即使传入了```initialData```，data的返回值中还是会```| undefined```，导致实际使用接口数据的时候，需要加入非空校验；
```
declare type State<R, P> = {
    loading: Ref<boolean>;
    data: Ref<R | undefined>;
    error: Ref<Error | undefined>;
    params: Ref<P>;
};
```

### 建议的解决方案 Proposed Solution
期望在传入```initialData```时``` data```的类型去掉```undefined```,或者使用```initalData```的类型替代```undefined```

### 其他信息 Other information
https://github.com/AttoJS/vue-request/issues/165

**Comment by Tanimodori** [comment]
Duplicate of #165

**Comment by John60676** [comment]
Duplicate of https://github.com/AttoJS/vue-request/issues/165
