### ISSUE TITLE
[Feature Request]建议导出interface PaginationQueryResult以便项目中针对自己的情况进行简单封装,建议mutate加入全局配置(一个项目中数据响应格式基本都是一致的)

### ISSUE THREAD

**Issue by herofqy** [AttoJS/vue-request#196]
### 需求描述 Feature Description

建议导出interface PaginationQueryResult以便项目中针对自己的情况进行简单封装,建议mutate加入全局配置(一个项目中数据响应格式基本都是一致的)

**Comment by John60676** [comment]
v1 还是 v2 呢

**Comment by John60676** [comment]
This has been fixed in https://github.com/AttoJS/vue-request/commit/35b07a4ffa22aca2cac3d1c46a0f4b99e4d1f206
