### ISSUE TITLE
[Need Help]在轮询中如何更好地调用cancel函数

### ISSUE THREAD

**Issue by CS-liujf** [AttoJS/vue-request#198]
### 问题描述 Problem Description

我使用了轮询功能，想要的效果是当轮询得到的数据满足某个要求时就停止轮询，所以我在`Options.onSuccess`中判断得到的数据，然后适时调用cancel函数，如下面的代码所示

```ts
const {data, run, loading, cancel } = useRequest(getQrStatusReq, {
  pollingInterval : 2000,
  manual: true,
  onError:(error)=>{console.log(error)},
  onSuccess:(res)=>{
     if(res.data === 1){
        cancel()
        login()
     }
  }
});
```

但这样行不通，它并不能使轮询停止。这是我的第一个疑问，为什么不能？
于是我就换了一个方法，在watch函数中监测`data`，如果条件满足则调用cancel函数，这个方法可以达到要求，不过我想知道这个方法是否符合规范。因此，我的第二个疑问是在哪里去调用cancel函数才是符合规范的？

**Comment by John60676** [comment]
已经修复了，`onSuccess` 和 `onError` 应该能取消轮询才是正确的。待会会发个版

**Comment by CS-liujf** [comment]
> 已经修复了，`onSuccess` 和 `onError` 应该能取消轮询才是正确的。待会会发个版

原来如此，没想打是一个bug，等你发新版后我再试试
