### ISSUE TITLE
[Bug Report]官方文档typo

### ISSUE THREAD

**Issue by CS-liujf** [AttoJS/vue-request#205]
### Bug 描述 Bug description
官方文档中关于[loading状态](https://www.attojs.com/guide/documentation/loadingDelay.html#loadingkeep)一节，对于`loadingkeep`的说明有误：
> 如果请求时间少于指定的时间，则最终时间为展示的时间

### 代码重现 Reproduce
无

### 期望结果 Desired result
应该改为
> 如果请求时间少于指定的时间，则最终时间为**指定**的时间

### 其他信息 Other information
无

**Comment by John60676** [comment]
感谢勘误 ❤️

**Comment by John60676** [comment]
已修正
