### ISSUE TITLE
[Need Help]关于手动请求后验证数据

### ISSUE THREAD

**Issue by ottocsb** [AttoJS/vue-request#206]
### 问题描述 Problem Description
如下图，手动发起请求，场景需要根据data内的code判断状态是否正常，无法在run后直接判断，提示无此属性，打印data到网页上正常显示，是我的食用方法有问题吗?

### 其他信息 Other information
![image](https://github.com/AttoJS/vue-request/assets/83228451/f9e3b353-f243-416b-a486-be309127e3fd)

**Comment by John60676** [comment]
```js
await runAsync();
// ... other code
```

**Comment by ottocsb** [comment]
感谢您的回复，还有一个问题是关于封装的，如下图，我意识到这样封装不正确，因为只能在`{data}=testRequest(val,val)`时传递参数，通过`runAsync`传递无效，是因为我的封装的结构有问题吗？
![image](https://github.com/AttoJS/vue-request/assets/83228451/bb69a339-ded7-4df7-a984-efd64ac404f6)

**Comment by ottocsb** [comment]
我知道下图内也是不正确，我想知道这样封装该如何正确的传参
![image](https://github.com/AttoJS/vue-request/assets/83228451/1e6ce23c-335a-4ec8-acdc-652049206851)

**Comment by John60676** [comment]
1. `defineComponent()` 写法

```js
defineComponents({
  setup() {
    const { data, runAsync } = useRequest(service, options);

    async function someFunction() {
      await runAsync();
      // other code
    }

    return {
      data,
      someFunction,
      // ... and more
    };
  },
});
```

2. `<script setup>` 写法

```vue
<script setup>
const { data, runAsync } = useRequest(service, options);

async function someFunction() {
  await runAsync();
  // other code
}
</script>
```

3. Composables/组合式函数 写法

```js
export function useXXXX() {
  const { data, runAsync } = useRequest(service, options);

  async function someFunction() {
    await runAsync();
    // other code
  }

  return {
    data,
    someFunction,
    runAsync,
    // ... and more
  };
}
```

**Comment by ottocsb** [comment]
好的十分感谢
