### ISSUE TITLE
[Need Help] 对返回的数据进行修改

### ISSUE THREAD

**Issue by ZhangTomLiang** [AttoJS/vue-request#214]
<img width="459" alt="image" src="https://github.com/AttoJS/vue-request/assets/18275926/46aab4a9-4bba-40a6-a3c6-7a9befa84009">
<img width="566" alt="image" src="https://github.com/AttoJS/vue-request/assets/18275926/130d2cae-81e6-4c88-a23c-ffdafa3ff34d">
	
<a-doption v-for="(project, index) in data?.data?.list" :key="index">
	{{ project.name }}
</a-doption>

所以是这样使用吗，为什么template的data没有并没有拿到异步请求里的data.value.data.list，

**Comment by John60676** [comment]
Reference https://github.com/AttoJS/vue-request/issues/130
