### ISSUE TITLE
[Need Help] 只要将useRequest结果导出就报ts(4023)错误

### ISSUE THREAD

**Issue by XGAGX** [AttoJS/vue-request#217]
### 问题描述 Problem Description

想将service和useRequest二次封装方便使用,但发现只要将useRequest结果导出就报ts(4023)错误

### 其他信息 Other information

创建个新项目也是如此

可创建个新项目复现这个问题

```ts
import { useRequest } from 'vue-request'

export const newRequest = (service: () => Promise<any>) => useRequest(service)
```

错误信息:

导出的变量“newRequest”具有或正在使用外部模块“"xxxx/node_modules/vue-request/dist/types/index"”中的名称“QueryResult”，但不能为其命名。ts(4023)

环境:
vscode: 1.78.2
node: 16.17.1
typescript: 5.0.4

最小demo项目文件只要3个文件
如下

package.json

```json
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "typescript": "^5.0.4",
    "vue-request": "^2.0.2"
  }
}

```

tsconfig.json

```json
{
  "include": ["env.d.ts", "./**/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": "."
  }
}
```
demo.ts

```ts
import { useRequest } from "vue-request";

export const newRequest = (service: () => Promise<any>) => useRequest(service);

```

**Comment by John60676** [comment]
This has been fixed in https://github.com/AttoJS/vue-request/commit/35b07a4ffa22aca2cac3d1c46a0f4b99e4d1f206
