### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by woohs** [AttoJS/vue-request#220]
### 需求描述 Feature Description

是否支持多次触发请求，自动**取消**前面的请求？

### 建议的解决方案 Proposed Solution

竞态取消，当上一次 promise 还没返回时，又发起了下一次 promise，则会忽略上一次 promise 的响应

### 其他信息 Other information

参考ahook：https://ahooks.js.org/zh-CN/hooks/use-request/basic#%E5%8F%96%E6%B6%88%E5%93%8D%E5%BA%94

**Comment by John60676** [comment]
支持的喔
