### ISSUE TITLE
[Need Help] 如何在ready返回false时，清空数据？

### ISSUE THREAD

**Issue by xuxule33** [AttoJS/vue-request#221]
### 问题描述 Problem Description
ready 返回false时，清空data

**Comment by John60676** [comment]
不妨说说你的原始需求

**Comment by xuxule33** [comment]
@John60676
大致是这么一个需求，在用户选择了数据库后，显示对应表信息（所以用ready控制初始的时候不请求）。如果用户清空选择（此时ready为false），希望把对应的表信息也清空。最后用computed实现了，感觉相对合理。
![image](https://github.com/AttoJS/vue-request/assets/139669642/60b7e136-e24e-452b-b024-e2a1f5ee0889)

<img width="638" alt="image" src="https://github.com/AttoJS/vue-request/assets/139669642/d0989ad5-6198-40bd-8cee-a7eb290839cf">

**Comment by John60676** [comment]
👍
