### ISSUE TITLE
[Bug Report] isBreak 拦截请求后状态未被正确更新

### ISSUE THREAD

**Issue by ZiuChen** [AttoJS/vue-request#226]
### Bug 描述 Bug description

在插件中使用 onBefore 钩子对前置参数进行校验，并选择性拦截请求
拦截后，状态没有被正确重置

### 代码重现 Reproduce

我编写了一个插件 useBeforePlugin 来辅助完成 onBefore 生命周期中的参数校验与请求拦截功能
但是它并没有按预期工作：

- id 小于等于 2 时，请求会正常发起
- 大于 2 时会被 onBefore 拦截，但是可以看到被拦截时的 loadng 状态是错误的（应当为 false）

[Demo 链接](https://stackblitz.com/edit/vue-request-issue-is-break?file=src%2FApp.vue)

> CodeSandbox 的 demo 在fork后跑不起来 我用 Stackblitz 编写了一个用于复现的Demo

### 期望结果 Desired result

当插件在 onBefore 时返回 isBreak 为 true 时：
- 加载状态应当被重置
- 响应数据 data 应当被更新为 breakResult 的值

### 其他信息 Other information

https://github.com/AttoJS/vue-request/pull/225

https://github.com/AttoJS/vue-request/issues/204

**Comment by ZiuChen** [comment]
在 https://github.com/AttoJS/vue-request/pull/225 被 merge 之前，可以通过这样的操作来完成参数校验与请求拦截：
```ts
const { data, loading, mutate } = useRequest(, {
  onBefore(params) {
    // 参数校验
    if(true) {
      nextTick(() => {
        loading.value = false
        // mutate( ... )
      })
      return false
    }
  }
})
```

**Comment by John60676** [comment]
自定义插件中的 `onBefore` 钩子添加了`isReturn`参数，用于处理需要中止请求并返回自定义数据的情况。具体使用参考[useCachePlugin](https://github.com/AttoJS/vue-request/blob/master/src/core/plugins/useCachePlugin.ts)

**Comment by ZiuChen** [comment]
breakResult 直接被干掉了？
那如果有插件使用到了 breakResult 的就都需要调整了

**Comment by John60676** [comment]
这次更新本身就属于 breaking change，所以调整是无法避免的。而且自定义插件使用的人不多

**Comment by ZiuChen** [comment]
什么时候可以发版解决这个问题呢？👀
