### ISSUE TITLE
打包输出的`dist/index.es.js`能否兼容一下更低的es版本

### ISSUE THREAD

**Issue by he-zhiyong** [AttoJS/vue-request#23]
### 问题描述 Problem Description
源码里有一句可选链的语法，在打包编译的时候，babel也没转掉，现在项目中引入安装包需要单独处理此问题

### 其他信息 Other information

![image](https://user-images.githubusercontent.com/23294703/106839718-bf65fa80-66d9-11eb-9de9-73307771a19f.png)
![image](https://user-images.githubusercontent.com/23294703/106839868-fd631e80-66d9-11eb-922a-370f0bda5346.png)

**Comment by John60676** [comment]
哎，奇怪。我检查一下

**Comment by John60676** [comment]
你这是哪个版本

**Comment by he-zhiyong** [comment]
@John60676 最新的1.0.0-beta.7确实可以了，感谢！！
