### ISSUE TITLE
[Need Help] 使用useRequest时 怎么能够和promise.all一起使用?

### ISSUE THREAD

**Issue by alleluya-young** [AttoJS/vue-request#230]
### 问题描述 Problem Description

请教一下 如果有多个接口或者相同接口不同传参多次请求 需要用到promise.all处理返回结果 应该怎么写呢?

**Comment by John60676** [comment]
这种场景下更推荐你直接用 Axios

**Comment by alleluya-young** [comment]
> 这种场景下更推荐你直接用 Axios

嗯嗯 最后是这么写的 我开始的时候以为有类似[run1,run2,...]这样的用法
