### ISSUE TITLE
[Feature Request] 参数refreshDeps可以接受一个数组吗

### ISSUE THREAD

**Issue by zogwosh** [AttoJS/vue-request#231]
### 需求描述 Feature Description

因为watch是支持监听多个响应式状态的,refreshDeps这个字段是watch的语法糖,那么支持数组更符合使用习惯

**Comment by John60676** [comment]
支持的

https://www.attojs.com/api/#refreshdeps

**Comment by zogwosh** [comment]
明白,但是默认没有用deep深度监听,有什么办法能设置深度监听吗,
