### ISSUE TITLE
[Bug Report]在 ssr 中使用 useRequest 会导致内存泄漏

### ISSUE THREAD

**Issue by CjLaunch** [AttoJS/vue-request#233]
### Bug 描述 Bug description
<img width="1461" alt="image" src="https://github.com/AttoJS/vue-request/assets/160834388/e683499e-1bb6-4975-9839-9981c74a92ce">
如图在内存快照发现大量 createQuery创建的实例未被GC回收，注销插件代码后，内存恢复正常。
<img width="559" alt="image" src="https://github.com/AttoJS/vue-request/assets/160834388/d6f46278-a2d2-4d27-956b-25a5619d762b">

**Comment by John60676** [comment]
可以提供一个重现示例吗

**Comment by CjLaunch** [comment]
目前排查下来发现是 usePollingPlugin 的插件导致的内存泄漏
<img width="511" alt="image" src="https://github.com/AttoJS/vue-request/assets/160834388/47c25b9b-70fc-4fb5-a6ca-816bc446a424">
<img width="1461" alt="image" src="https://github.com/AttoJS/vue-request/assets/160834388/6cb081b1-f93c-4c44-b662-00afcedeedeb">

**Comment by John60676** [comment]
如果可以的话，能否提交个PR？
