### ISSUE TITLE
[Feature Request] 请求对EffectScope的支持

### ISSUE THREAD

**Issue by s3xysteak** [AttoJS/vue-request#239]
### 需求描述 Feature Description

希望能支持EffectScope以获取广泛的使用场景

[vue文档](https://cn.vuejs.org/api/reactivity-advanced.html#effectscope)

在Vue3中setup是基于EffectScope的，所以这应该是一个非破坏性更新，但是可以扩展很多使用场景

### 建议的解决方案 Proposed Solution

大概看了一下vue-request的代码，看起来似乎只需要将`onUnmounted`替换为`onScopeDispose`即可

### 其他信息 Other information

onScopeDispose看起来是vue3特有的概念，vue2没有，因此vue-demi好像也没有这个方法。为了解决这个问题可以写一个函数：

```js
import { isVue3, onUnmounted } from 'vue-demi'

function tryOnScopeDispose(fn) {
  isVue3 ? onScopeDispose(fn) : onUnmounted(fn)
}
```

作为onUnmounted的替代

**Comment by s3xysteak** [comment]
这是其使用场景

Before:
```js
const { data } = useRequest(reqA)

const map = {
  1: () => {
    useRequest(reqB)
  },
  2: () => {
    useRequest(reqC)
  }
}

watch(data, (types) => {
  types.forEach(type => map[type]()) // ！这里超出了setup周期！
})
```

After:
```js
const scope = effectScope()
const { data } = useRequest(reqA)

const map = {
  1: () => {
    useRequest(reqB)
  },
  2: () => {
    useRequest(reqC)
  }
}

watch(data, (types) => {
  scope.run(() => {
    types.forEach(type => map[type]()) // ! GOOD !
  })
})

onUnmounted(() => scope.stop())
```

**Comment by John60676** [comment]
当时2.0是有计划替换成 `onScopeDispose` 后面基于什么原因导致没替换，我可能还需要再查看一下。如果确认能替换的话，可能会在 2.1 版本上线。
