### ISSUE TITLE
[Need Help] 关于 usePagination的疑问

### ISSUE THREAD

**Issue by like0413** [AttoJS/vue-request#240]
### 问题描述 Problem Description

我按照ant design 的示例：

```vue
<script lang="ts" setup>
import type { TableProps } from 'ant-design-vue'
import { getDemoTable } from '@/api/demo'

const columns = []

const {
  data,
  run,
  loading,
  current,
  pageSize,
  total
} = usePagination(getDemoTable, {
  pagination: {
    currentKey: 'ext.page',
    pageSizeKey: 'ext.size',
    totalKey: 'ext.total',
  },
})
const dataSource = computed(() => data.value?.list ?? [])

const pagination = computed(() => ({
  total: total.value,
  current: current.value,
  pageSize: pageSize.value,
}))

const onTableChange: TableProps['onChange'] = (pag, filters, sorter) => {
  run({
    page: pag.current,
    size: pag.pageSize,
    sorter: sorter,
    ...filters,
  })
}
</script>

<template>
  <a-table
    :row-key="(record) => record.id"
    :columns="columns"
    :data-source="dataSource"
    :pagination="pagination"
    :loading="loading"
    @change="onTableChange"
  ></a-table>
</template>

<style scoped lang="scss"></style>

```

这是接口的返回结构：
![image](https://github.com/AttoJS/vue-request/assets/48686374/26291316-42d1-45c1-8e4d-5b9c14cc3177)

我的疑惑：
初次时参数是这样的：
![image](https://github.com/AttoJS/vue-request/assets/48686374/35ac41eb-e194-4ffd-a3a3-7c59244f221b)
点击分页时是这样的：
![image](https://github.com/AttoJS/vue-request/assets/48686374/8a0e7f16-4480-4514-98ec-c1c6f94a5e27)

我不太理解初次的传参为什么是这样

**Comment by John60676** [comment]
`currentKey` 和 `pageSizeKey` 在你这个例子中应该填的是  'page'  和  'size'，它们是 `getDemoTable` 请求函数的形参名

**Comment by like0413** [comment]
> `currentKey` 和 `pageSizeKey` 在你这个例子中应该填的是 'page' 和 'size'，它们是 `getDemoTable` 请求函数的形参名

如果填 'page' 和 'size'，就不匹配我的返回值了，值是在ext里的

**Comment by John60676** [comment]
匹配的是接口的入参，不是返回值

**Comment by like0413** [comment]
感谢。文档我没看仔细，也是没想到pagination既有入参也有返回值
