### ISSUE TITLE
[Need Help] 关于defaultParams不是响应式的疑问

### ISSUE THREAD

**Issue by like0413** [AttoJS/vue-request#244]
### 问题描述 Problem Description
问题来源于这个：https://github.com/AttoJS/vue-request/issues/187

1、如果每次运行run都要重新传参，比较麻烦
2、如果getUser参数不止一个，那在run的时候就需要重新构造参数并考虑传参顺序，心智负担比较大啊

我水平有限，想了解下，没有设计响应式参数的原因是？

**Comment by John60676** [comment]
> 如果每次运行run都要重新传参，比较麻烦

稍微封装一下即可解决你提出的那两个问题
```js
function handleSearch() {
  const { name, status } = searchParams.value;
  runAsync({
    name,
    status,
  });
}
```

> 没有设计响应式参数的原因是？

没必要把一件简单的事情复杂来做，如果想根据 请求参数的变化响应触发请求的，完全可以在业务层面上，自己利用 `watch` 来实现
