### ISSUE TITLE
单文件组件中使用 queries 请求返回的数据需要通过 .value 获取

### ISSUE THREAD

**Issue by lzj97** [AttoJS/vue-request#29]
### Bug 描述 Bug description
在vue单文件组件中使用 queries 请求返回的数据需要通过 .value 获取
```js
    <span v-if="queries[i.id]?.loading.value">loading...</span>
    <span v-else> {{ queries[i.id]?.data.value }}</span>

```

### 代码重现 Reproduce
https://codesandbox.io/s/awesome-easley-nwydw?file=/src/App.vue

### 期望结果 Desired result
能直接通过`queries[id].loading` 、 `queries[id].data` 获取数据

**Comment by John60676** [comment]
fix in `beta.10`
