### ISSUE TITLE
onSuccess方法的入参data无法获取正确的type

### ISSUE THREAD

**Issue by joker77877** [AttoJS/vue-request#31]
### Bug 描述 Bug description
onSuccess方法的入参data无法获取正确的type

### 代码重现 Reproduce
![531615877457_ pic_hd](https://user-images.githubusercontent.com/62642184/111267725-53c36580-8667-11eb-823d-9741da342199.jpg)
![541615877516_ pic_hd](https://user-images.githubusercontent.com/62642184/111267740-58881980-8667-11eb-8761-c31472c2eb26.jpg)
![551615877742_ pic](https://user-images.githubusercontent.com/62642184/111268016-b288df00-8667-11eb-8b82-475c5ee1c0db.jpg)

### 期望结果 Desired result

onSuccess方法的入参data可以获取正确的type

**Comment by John60676** [comment]
`onSuccess` 的类型推断有点问题。

临时解决方案： 可以手动给 `useRequest` 提供泛型，代码如下

```ts
    const { data } = useRequest<string, any, number>(testService, {
      formatResult: res => Number(res),
      onSuccess: data => {
        // `data` type is number
      },
    });
```

**Comment by joker77877** [comment]
这样可以但是我要再次写一次类型，希望还是完善一下类型的推断。
![561615954748_ pic](https://user-images.githubusercontent.com/62642184/111414457-01438100-871b-11eb-90df-861fb5035413.jpg)
再问下这里的data设置了initialData依旧有undefined的类型

**Comment by John60676** [comment]
> 问题一：这样可以但是我要再次写一次类型，希望还是完善一下类型的推断。

目前出现这个问题只会在 `formatResult` 和 `onSuccess` 同时使用的情况下。看了一下还没有完美的解决方案。后续可能先会把 `onSuccess` 的 data 入参设置成 `any`，等找到方法再进行修复。

其实按照你提供的代码截图，你这段代码可以不使用 `onSuccess` 来处理的，直接用 `watch` 去监听 `data` 即可


> 问题二：data设置了initialData依旧有undefined的类型

这是 ts 的问题。如果你能确保 `data.value` 不为 `undefined` 的话，你可以加个 [非空断言](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator)，即 `data.value!`。后续再考虑一下看看是否需要把 `data` 和 `error` 的 `undefined` 移除

**Comment by joker77877** [comment]
好的谢谢你的解答

**Comment by John60676** [comment]
这 issue 挂着吧。免得我忘了😆

**Comment by John60676** [comment]
已发布：1.0.5

**在 formatResult 和 onSuccess 同时使用的情况下**，onSuccess 的 data 入参设置成 any，如果想要 onSuccess 有类型提示的，可以显式传入第三个泛型， 参考

```ts
    const { data } = useRequest<string, any, number>(testService, {
      formatResult: res => Number(res),
      onSuccess: data => {
        // `data` type is number
      },
    });
```


上面提到的改动仅在 formatResult 和 onSuccess 同时使用，且没显式提供泛型 的情况下，其他用法均不受影响

**Comment by joker77877** [comment]
我更新为1.0.5之后还是有点问题
![581616483963_ pic_hd](https://user-images.githubusercontent.com/62642184/112108439-2b99b080-8beb-11eb-92d7-a766d9d009ae.jpg)
我没有给useRequest传入三个泛型，但是我的getDetail确实已经将泛型传入useRequest，并且指向onSuccess也上图所示已经显示data的类型，但是当我指向data时他依然是any,是一定要显式传入第三个泛型data才能显示正确类型吗。
![image](https://user-images.githubusercontent.com/62642184/112108674-7c110e00-8beb-11eb-9a0a-71343f89dbc8.png)

**Comment by John60676** [comment]
是的，这个行为确实很怪异，鼠标移上去时他是能把正确类型推断出来的，但是实际使用时却是没有正确的类型，这个目前也没有很好的解决方案。至于 any 这是我们内部做了处理。如果内部不把 onSuccess 的入参类型改成any，让其自动推断的话，会导致 resultValue 里面的 data 丢失类型。所以为了确保 resultValue 的 data 类型正确，我们再 1.0.5 版本暂时以这个方案修复了


其实看你截图的代码，你这个需求貌似可以用 vue 的 watch 来实现

**Comment by joker77877** [comment]
是的，我这个需求用watch实现了，但是只有onSuccess的时候data类型就正确。

**Comment by John60676** [comment]
> 是的，我这个需求用watch实现了，但是只有onSuccess的时候data类型就正确。

1.0.5 做了以下的修改

**在 formatResult 和 onSuccess 同时使用的情况下**，onSuccess 的 data 入参设置成 any，如果想要 onSuccess 有类型提示的，可以显式传入第三个泛型。

单独使用 onSuccess 是不受影响的，自动推断也是正常的

**Comment by joker77877** [comment]
![image](https://user-images.githubusercontent.com/62642184/121289504-9b305980-c917-11eb-92c4-5ca85dd3f269.png)
defaultParams和onSuccess同时使用报错 没有与此调用匹配的重载

**Comment by John60676** [comment]
没能重现哦。提供个能重现的可运行示例看看

**Comment by joker77877** [comment]
onSuccess函数中加入参数就会出现这个ts报错

**Comment by John60676** [comment]
![image](https://user-images.githubusercontent.com/21698973/121501820-2857d900-ca12-11eb-8722-82faef2cd7a5.png)
