### ISSUE TITLE
无法正确的拿到data值

### ISSUE THREAD

**Issue by 99414041** [AttoJS/vue-request#32]
### Bug 描述 Bug description
打印data为undefined

### 代码重现 Reproduce
 const { data, loading } = useRequest(APICESHI);
      console.log(data.value);

### 期望结果 Desired result
可以拿到data的值

**Comment by John60676** [comment]
请求是一个异步操作来的。

简单来说就是，你这个请求都还没结束，肯定是 `undefined` 的。。。

你直接绑在页面用就好了，`data` 的值是响应式的

**Comment by 99414041** [comment]
```
const count = ref(1);
useRequest({
   url: '/ceshi',
   data: {c: count}
}, {
   refreshDeps: [count]
});
setTimout(() => count++, 1000);
```
data为什么不会更新啊，一直是1

**Comment by 99414041** [comment]
> 请求是一个**异步**来的。
> 
> 简单来说就是，你这个请求都还没结束，肯定是 `undefined` 的。。。
> 
> 你直接绑在页面用就好了，`data` 的值是响应式的

关键是await都拿不到

**Comment by 99414041** [comment]
还想请教一个问题，我在test里只能拿到更新的data, 拿不到url，辛苦帮忙看一下
```
/* useApi.js */
import { useRequest } from 'vue-request';
import axios from 'axios';

funcition test(params) {
  axios.request({url: params.url, data: params.data})
}

export default function useFetch (opt) {
  return useRequest(testService, { ...opt });
}
```

```
/* main.js */
import useFetch from './useFetch';
setup() {
  const name = ref('');
  const { run } = useFetch({ url: '/test', data: {name: name.value} });
  
 const handleSubmit = () => run(name.value);
}
```

```
/* main.vue */
<template>
  <input v-model="name" />
  <button @click="handleSubmit">提交</button>
</template>
```

**Comment by benny-eu** [comment]
你需要在执行`run`方法时传入参数。

改成这样即可：

```ts
const handleSubmit = () => run({ url: '/test', data: {name: name.value} });
```

**Comment by John60676** [comment]
> 关键是await都拿不到

请求我们内部已经帮你接管了，你就不用管，我们也没有把异步抛出来，所以你的 `await` 也不会有效果。如果你真的想拿 `data` 来用的，你可以在 [`onSuccess`](https://www.attojs.com/zh/api/#onsuccess)里获取  或者 在使用 Vue 的 `watch` 、 `computed` 等。或者你可以先去看看我们的文档，里面的示例都是有代码可以自己拿来运行的。 文档地址： https://www.attojs.com/

**Comment by 99414041** [comment]
> > 关键是await都拿不到
> 
> 请求我们内部已经帮你接管了，你就不用管，我们也没有把异步抛出来，所以你的 `await` 也不会有效果。如果你真的想拿 `data` 来用的，你可以在 [`onSuccess`](https://www.attojs.com/zh/api/#onsuccess)里获取 或者 在使用 Vue 的 `watch` 、 `computed` 等。或者你可以先去看看我们的文档，里面的示例都是有代码可以自己拿来运行的。 文档地址： https://www.attojs.com/

好的，感谢

**Comment by 99414041** [comment]
> 你需要在执行`run`方法时传入参数。
> 
> 改成这样即可：
> 
> ```ts
> const handleSubmit = () => run({ url: '/test', data: {name: name.value} });
> ```

好的，辛苦了
