### ISSUE TITLE
typescript文件报错

### ISSUE THREAD

**Issue by joker77877** [AttoJS/vue-request#33]
### Bug 描述 Bug description

检测项目ts类型报错

### 代码重现 Reproduce

![571616385402_ pic](https://user-images.githubusercontent.com/62642184/111938863-ddf74800-8b05-11eb-8464-1f00d4d4a139.jpg)

### 期望结果 Desired result

不报错

**Comment by John60676** [comment]
这好像是打包的问题，下个版本修复

**Comment by John60676** [comment]
已修复： 1.0.5
