### ISSUE TITLE
[Need Help]

### ISSUE THREAD

**Issue by shumyun** [AttoJS/vue-request#34]
### 问题描述 Problem Description
分页功能在setup函数内自动第一次获取数据，得到current是0，不是文档中的1。

**Comment by John60676** [comment]
我没能重现你的问题

参考：https://codesandbox.io/s/charming-bartik-tedcc?file=/src/App.jsx

你可以提供一下你的重现代码

**Comment by shumyun** [comment]
用的是antdv。
`

export function getContracts(dataInfo) {
  return request({
    url: contractApi.list,
    method: 'post',
    data: dataInfo,
    headers: {
      'Content-Type': 'application/json;charset=UTF-8',
    },
  });
}

    const { run, loading, total, current, pageSize } = usePagination(getContracts, {
      formatResult: (res) => {
        console.log(res);
        data.value = res.data;
        return res;
      },
      defaultParams: [{ queryParam }],
      pagination: {
        totalKey: 'count',
        currentKey: 'curPage',
      },
    });

    const pagination = computed(() => ({ total: total.value, current: current.value, pageSize: pageSize.value }));
`

**Comment by John60676** [comment]
没有问题啊。这是我在 antdv 文档里面提供的一个示例，[远程加载数据](https://2x.antdv.com/components/table-cn#components-table-demo-ajax)。你自己拿来跑一下看看

https://codesandbox.io/s/aged-sea-g7w1p?file=/src/App.vue  或者你在 codesandbox 里面重现一下你的问题，然后把链接发上来

**Comment by John60676** [comment]
没能提供重现的话，我这边先关掉 ISSUE
