### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Liu-Ya** [AttoJS/vue-request#35]
### 需求描述 Feature Description

希望 run 返回 Promise，现在无论执行成功与否都会走到 then

比如批量删除和删除使用同一个请求，但返回后触发不同操作，不适用 onSuccess

### 建议的解决方案 Proposed Solution

```js
run({}).then(res => {
  // do something
}).catch(err => {})
```

**Comment by John60676** [comment]
`onSuccess` 和 `onError`本质上对应的就是 `run` 的 `then` 和 `catch`。你直接在 `onSuccess` 里面处理业务就好了。`run.then` 不建议直接使用，有些特殊情况`then`的`res`的值会是`null`，参考：https://www.attojs.org/zh/api/#run

**Comment by Liu-Ya** [comment]
> `onSuccess` 和 `onError`本质上对应的就是 `run` 的 `then` 和 `catch`。你直接在 `onSuccess` 里面处理业务就好了。`run.then` 不建议直接使用，有些特殊情况`then`的`res`的值会是`null`，参考：https://www.attojs.org/zh/api/#run

使用 axios resolve() 的时候没有触发onSuccess 反而触发了 onError 是设计如此吗？

**Comment by John60676** [comment]
新开一个 issue,提供一个重现 demo。
