### ISSUE TITLE
[Feature Request] useLoadMore 支持不清空 dataList 从第一页重新加载数据

### ISSUE THREAD

**Issue by keuby** [AttoJS/vue-request#36]
### 需求描述 Feature Description

`useLoadMore` 使用时，每次下拉刷新调用 reload 方法都会清空掉 dataList 数据重新加载，但是在大多数情况下，下拉刷新的操作数据其实不会变化，这样每次下拉刷新列表操作都会闪动一下（数据消失，接口调用成功之后再展示相同的内容），比较影响用户体验

### 建议的解决方案 Proposed Solution

建议新增一个 refresh 方法，覆盖掉现有的 refresh 方法用来做下拉刷新，该方法调用后，重新从第一页加载数据的同时不会清空掉 dataList 的内容，而是在接口调用成功之后直接替换掉 dataList 的原有内容

**Comment by John60676** [comment]
这个提议好 👍

**Comment by keuby** [comment]
目前 useLoadMore 方法返回的字段中，有 `loading` 和 `loadingMore` 用于标识加载状态，`loading` 是每次发送请求都会改变为 true，loadingMore 是上拉加载时会为 true，现在没有一个状态用于下拉刷新的加载状态

我尝试直接使用 `loading` 作为下拉刷新的加载状态，但是这样在第一次加载数据的时候 loadingMore 和 loading 会同时 为 true，这样就会导致下拉刷新和上拉加载的加载动画会同时显示

**Comment by John60676** [comment]
功能已实现，下个版本发布
