### ISSUE TITLE
Support Vue 2

### ISSUE THREAD

**Issue by John60676** [AttoJS/vue-request#38]
### Feature Description

Use [`composition-api`](https://github.com/vuejs/composition-api) to be compatible with Vue 2

**Comment by ModyQyW** [comment]
或许可以考虑一下 [vue-demi](https://github.com/vueuse/vue-demi)？:D

**Comment by John60676** [comment]
这个有考虑过，我都实现一遍。最后看看采取什么方案比较好

**Comment by byoungd** [comment]
> 这个有考虑过，我都实现一遍。最后看看采取什么方案比较好

Does it support Vue2 now or when will it be released?

**Comment by John60676** [comment]
@byoungd 
😅  Not sure. But hoping to make at least alpha release soon enough!

**Comment by CracKerMe** [comment]
期待 vue2 的实现

**Comment by John60676** [comment]
> 你好，尝试了一下vue-demi的方式实现同时支持vue2和3，目前看起来是能用，除了vue2下需要在src目录中加入shims.d.ts来规避defineComponent导致的编译错误
> 
> ```js
> declare module '*.vue' {
>     import { defineComponent } from '@vue/composition-api';
>     const component: ReturnType<typeof defineComponent>;
>     export default component;
> }
> ```
> 
> 这是我fork出来的分支地址https://github.com/kylee0325/vue-request/tree/compatible 你可以看下是否能帮上忙，如有问题，也请知会一下。

感谢，2.0 已经在做了

**Comment by luyi2008** [comment]
Hello John. Is there a release schedule?

**Comment by John60676** [comment]
I hope to have an alpha release by April.

**Comment by John60676** [comment]
[2.x Roadmap](https://github.com/AttoJS/vue-request/projects/2)

**Comment by John60676** [comment]
alpha 版本已发布
