### ISSUE TITLE
[Bug Report] usePagination manual 为 true 时，defaultParams: [{ pageSize: 50 }] 无效

### ISSUE THREAD

**Issue by Liu-Ya** [AttoJS/vue-request#40]
### Bug 描述 Bug description

当 `manual: true` 时设置的`defaultParams: [{ pageSizeKey: 50 }]`不生效，获取到的 `pageSize` 为10

### 代码重现 Reproduce

```
      const {
        current,
        total,
        loading,
        pageSize,
        changeCurrent,
        changePageSize,
        run: fetchData,
      } = usePagination(fetchOrderList, {
        // manual: true,
        defaultParams: [{ pageSize: 50, page: 1 }],
        pagination: { currentKey: 'page', pageSizeKey: 'pageSize', totalKey: 'total' },
        onSuccess: (res) => {
          gridOptions.value.api?.setRowData(res.data);
        },
      });
```

### 期望结果 Desired result

获得的 `pageSize` 默认为 50

**Comment by John60676** [comment]
噢，好像是有点问题，我再看看

**Comment by John60676** [comment]
[`defaultparams`](https://www.attojs.org/zh/api/#defaultparams) 只会在 `manual: false` 时生效。至于在 `usePagination` 中使用时，我觉得可以讨论一下

**Comment by Liu-Ya** [comment]
> [`defaultparams`](https://www.attojs.org/zh/api/#defaultparams) 只会在 `manual: false` 时生效。至于在 `usePagination` 中使用时，我觉得可以讨论一下

确实不应该在 `manual: true` 时生效，我看调用 `run` 时也是要自己传入分页的，现在逻辑没错

在 `usePagination`  的`pagination` 中添加一个配置项 如 `defaultPageSize`、`defaultCurrent` 应该是可以的，当`manual: false`时`defaultParams` 比 `pagination.defaultPageSize` 优先级高

**Comment by John60676** [comment]
下个版本修复

**Comment by John60676** [comment]
已发布 [v1.1.1](https://www.npmjs.com/package/vue-request/v/1.1.1)
