### ISSUE TITLE
Add hooks before and after request

### ISSUE THREAD

**Issue by John60676** [AttoJS/vue-request#42]
## Usage

```jsx
const request = useRequest(server, {
  onBefore(params) {},
  onAfter(params) {},
})
```

### Options

| Property | Description         | Type                  | Default |
| -------- | ------------------- | --------------------- | ------- |
| onBefore | Hook before request | `(params: P) => void` | -       |
| onAfter  | Hook after request  | `(params: P) => void` | -       |

**Comment by keuby** [comment]
@John60676 `onBefore` 钩子在request 之前就直接执行了，而且 loading 这个时候可能还没有触发，如果直接在这个时候去执行显示loading的话，会出现 loading 闪现的情况

```typescript
  const delayLoading = () => {
    let timerId: number;

    if (loadingDelay) {
      timerId = setTimeout(setState, loadingDelay, {
        loading: true,
      });
    }

    return () => timerId && clearTimeout(timerId);
  };
```
不知道能不能再这里有什么东西可以检测到 loading 的变化

**Comment by John60676** [comment]
@keuby  有了 `onBefore` 和 `onAfter` 后，其实可以自己封装 `loading`

**Comment by keuby** [comment]
>有了 onBefore 和 onAfter 后，其实可以自己封装 loading

嗯，这个没啥问题，不过要是可以提供一个 util 来实现这个功能的话可能会更好，例如暴露出来一个方法 

```typescript
import { getGlobalOptions } from 'core/config'

/**
 * 延迟执行
 * 
 * @param cb 延迟执行的回调函数
 * @param loadingDelay 延迟执行时间，不传则默认为 Global 设置的时间
 * @returns 调用提前取消回调函数执行
 */
export function delayedExec(cb: () => void, loadingDelay?: number): () => void {
    let timerId: number;

    if (loadingDelay) {
      timerId = setTimeout(() => {
        cb();
        timerId = null;
      }, loadingDelay ?? getGlobalOptions().loadingDelay);
    }

    return () => timerId && clearTimeout(timerId);
}
```

> ps: 函数名可以取个更好的  [手动狗头.png]

而且这个方法的功能其实现在外部是没办法完全实现的，因为我们拿不到 getGlobalOptions 这个方法，这个 loadingDelay 的值除了 setGlobalOptions 那边写了一遍以外，这边可能还得再写一遍

**Comment by John60676** [comment]
但是这个 `config` 目前还没有想到特别好的方案能暴露出去，等我后续再研究一下。如果你有好的方案，欢迎来个PR😁

目前希望的API形式是
``` js
const request = useRequest(server, {
  onBefore(params, config) {},
  onAfter(params, config) {},
})
```

**Comment by John60676** [comment]
[v1.2.0](https://www.npmjs.com/package/vue-request/v/1.2.0) 已发布
