### ISSUE TITLE
[Need Help] usePagination 如何同时修改 current 和 pageSize

### ISSUE THREAD

**Issue by Liu-Ya** [AttoJS/vue-request#43]
### 问题描述 Problem Description

当需要同时改变 `current` 和 `pageSize` 时是不是应该只发起一次请求？

场景

![image](https://user-images.githubusercontent.com/23520283/117415960-7b3dfc80-af4b-11eb-986c-e6cf19d679e6.png)

当如上图的页码，切换为 200条/页 时，分页器会将 页码切换到可用的最后一页  如下

![image](https://user-images.githubusercontent.com/23520283/117417392-e0deb880-af4c-11eb-9478-b397155bd180.png)

为了保证数据可用，不管是使用分页器的方案还是自己重新计算下可用页码都需要同时调用 `changeCurrent` 和 `changePageSize`，此时会触发两次请求

**Comment by Liu-Ya** [comment]
```js
const { params, run } = usePagination(fetch, {...})

const onPageSizeChange = (current, pageSize) => {
  run({...params[0], current, pageSize})
}
```

好像可以用这种写法，完全抛掉`changePageSize`了，不过有点麻烦

**Comment by John60676** [comment]
确实是有这种现象，我们决定新增一个方法，用来同时修改 `current` 和 `pageSize`。

但是也有一些组件库会有一些怪异行为。例如 element 的 pagination 组件，出现上述情况时会同时触发组件库的 `currentChange` 和 `sizeChange` 这种情况只能自己去控制一下了

**Comment by John60676** [comment]
[v1.2.0](https://www.npmjs.com/package/vue-request/v/1.2.0) 已发布
