### ISSUE TITLE
typescript下axios和useRequest怎么整合

### ISSUE THREAD

**Issue by dmyz** [AttoJS/vue-request#50]
### 问题描述 Problem Description

  let api: Promise<AxiosResponse<any>> = axios.get('api/user');
  return useRequest(api);

![image](https://user-images.githubusercontent.com/15307200/122323810-45346500-cf5a-11eb-80d2-a19648e315dd.png)

**Comment by John60676** [comment]
参考 https://www.attojs.com/guide/documentation/default-request.html#%E4%BC%A0%E5%85%A5%E8%AF%B7%E6%B1%82%E5%87%BD%E6%95%B0
