### ISSUE TITLE
usePagination 的 formatResult 能否在取完 total,current,pageSize 之后调用

### ISSUE THREAD

**Issue by zoyen** [AttoJS/vue-request#52]
我使用 `formatResult: ({ list }) => list` 让 `data` 直接是数组

total,current,pageSize 等数据 usePagination 已经提供，`data` 中不需要

或者有其他方式吗？

**Comment by John60676** [comment]
建议用 `computed` 处理一下 `data`

**Comment by zoyen** [comment]
好吧，谢谢，已经封装了一层。

我是不想在组件内产生多余的变量，我使用全都是 usePagination 外面套一层 reactive

`const x = reactive(usePagination())`
`x.data`
`x.run()`
