### ISSUE TITLE
usePagination 设置每页记录数问题

### ISSUE THREAD

**Issue by 754139416** [AttoJS/vue-request#53]
请问 usePagination 怎么才能设置返回的每页记录数呢？如果我用 usePagination返回的changePageSize设置为 changePageSize(20) 这样设置，第一次进入页面时，要访问两次服务器，第一次是https://randomuser.me/api?noinfo&results=10&page=1，第二次是 https://randomuser.me/api?noinfo&results=20&page=1，只有翻页时，才会执行一次，即https://randomuser.me/api?noinfo&results=20&page=2
是我用的不对吗？

**Comment by zoyen** [comment]
请查看文档中的 手动请求: [https://www.attojs.com/guide/documentation/manual.html](url)

**Comment by John60676** [comment]
太久没回应，先 close 了
