### ISSUE TITLE
[Need Help] 在路由生命周期 beforeRouteEnter 钩子内部是否可以使用 useRequest ?

### ISSUE THREAD

**Issue by keuby** [AttoJS/vue-request#55]
### 问题描述 Problem Description

我希望在 beforeRouteEnter 钩子里面调用接口获取数据，然后在拿到数据字后调用 next 方法，拿到 vm 实例将数据交给 vm 直接渲染。是否可以在 beforeRouteEnter 钩子里面使用 useRequest 方法呢？

我看到源码里面有使用到 watch watchEffect 这样的函数，这样的函数在 setup 函数之外调用是否会有意外发生。我担心 watchEffect  在 setup 之外使用无法正常停止侦听。

**Comment by John60676** [comment]
暂时不支持，因为内部有依赖 Vue 的生命周期
