### ISSUE TITLE
关于在 setup 方法外部使用 useRequest 的实现探索

### ISSUE THREAD

**Issue by keuby** [AttoJS/vue-request#56]
### 需求描述 Feature Description

目前 useRequest 只能在 setup 内部使用，但是 Vue 3.2 中新增的 [EffectScope](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0041-reactivity-effect-scope.md) 给 useRequest 在组件外部使用增加了可能，在结合 [vueuse#tryOnUnmounted](https://vueuse.org/shared/tryOnUnmounted/#tryonunmounted) 类似的实现，我想是不是可以提供一个 dispose 方法，以面对在setup方法外部使用 useRequest 的场景，让用户可以手动去解除监听和释放内存

**Comment by keuby** [comment]
细想一下其实就算没有 EffectScope 其实也可以实现一个 dispose 方法暴露出去让用户手动释放内存以及停止数据监听

**Comment by John60676** [comment]
有什么场景需要在组件外部使用的吗

**Comment by keuby** [comment]
比如，我想要在 beforeRouterEnter 中调用接口。

**Comment by keuby** [comment]
@John60676 根据 [rfc#41](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0041-reactivity-effect-scope.md#onscopedispose)的描述，我感觉是不是只需要将 onUnmounted 改为 onScopeDispose 就可以直接支持，不过这样子做可能需要对低版本 vue 做部分兼容

**Comment by John60676** [comment]
考虑了一下，在路由里面请求的场景实在不多，而且加这个功能可能会使得 useRequest 变得繁重起来，不利于后续的更新。后续将打算兼容 Vue 2.7 的

**Comment by callmez** [comment]
场景外的需求是有的 而且很普遍. 

目前我们在`Vuex`中 是没办法`useRequest`的 但是`store.actions`又可能会有多`actions`联动并请求接口的场景.  

Vue3的createApp 虽然做到了全局app实例的隔离. 
因为无法确定插件调用时当前所在的Vue instance scope.  实际上增加了Vue插件间的依赖和访问成本(很多插件 都是自注册全局实例来解决这个问题. 比如 `pinia`使用`setAcitvePinia()`注册并在外部使用). 
`EffectScope`就是解决这个问题而生. 


不过个人觉得并不是一个完美的方案. 不过能解决主要问题已经可以了

**Comment by John60676** [comment]
2.0 版本会使用 `onScopeDispose` 替代 `onUnmounted`，届时如果有其他需求的可自行实现

**Comment by Preyou** [comment]
> 2.0 版本会使用 `onScopeDispose` 替代 `onUnmounted`，届时如果有其他需求的可自行实现

好像依然不行啊，还是有警告

**Comment by KaneOne** [comment]
感觉这个场景还是有的，比如一个页面中的多个子组件同时调用了一个接口，在底层用useRequset封装这个接口来实现缓存和保鲜时间，减少对后端的并发请求。

**Comment by John60676** [comment]
> 感觉这个场景还是有的，比如一个页面中的多个子组件同时调用了一个接口，在底层用useRequset封装这个接口来实现缓存和保鲜时间，减少对后端的并发请求。

https://www.attojs.com/guide/documentation/cacheKey.html#%E8%AF%B7%E6%B1%82%E5%85%B1%E4%BA%AB
这能解决你的痛点

**Comment by KaneOne** [comment]
> > 感觉这个场景还是有的，比如一个页面中的多个子组件同时调用了一个接口，在底层用useRequset封装这个接口来实现缓存和保鲜时间，减少对后端的并发请求。
> 
> https://www.attojs.com/guide/documentation/cacheKey.html#%E8%AF%B7%E6%B1%82%E5%85%B1%E4%BA%AB 这能解决你的痛点

谢谢大佬回复，这个用法我知道，我现在是在外部的ts里封装了这个方法给多个组件引用，如下：
```
import { useRequest } from 'vue-request';

//这里会出现下面图片里的警告
const { runAsync } = useRequest(getUserInfo, {
  manual: true,
  cacheKey: 'userinfo',
  staleTime: 2000,
});

export getUserInfoByRequest=()=>{
  return await runAsync();
}
```

![image](https://github.com/AttoJS/vue-request/assets/1954595/0cc10019-7ae0-4d1a-a6f0-e8b5ab58ec64)


主要还是vue-request已经满足了对于请求封装的需求，所以想直接拿来使用，不再去封装axios了，请大佬看看。

**Comment by John60676** [comment]
```js

function useUserInfo(){
  const { runAsync } = useRequest(getUserInfo, {
    manual: true,
    cacheKey: 'userinfo',
    staleTime: 2000,
  });
  
  return {
    // export what you want
    getUserInfoByRequest: runAsync
  }
}



// setup script

const { getUserInfoByRequest } = useUserInfo();

getUserInfoByRequest()

```

**Comment by KaneOne** [comment]
感谢大佬，另外跟上面的帖子一样，有些请求是在store的action里面执行的，这个store被多个组件引用，如下图，这种场景确实没办法了吗？
![image](https://github.com/AttoJS/vue-request/assets/1954595/932e3dee-4492-4637-8d4d-f825ef3c3ce4)

**Comment by Zheng-Changfu** [comment]
> 感谢大佬，另外跟上面的帖子一样，有些请求是在store的action里面执行的，这个store被多个组件引用，如下图，这种场景确实没办法了吗？ ![image](https://private-user-images.githubusercontent.com/1954595/323496490-932e3dee-4492-4637-8d4d-f825ef3c3ce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTQ1MzMsIm5iZiI6MTczMzc1NDIzMywicGF0aCI6Ii8xOTU0NTk1LzMyMzQ5NjQ5MC05MzJlM2RlZS00NDkyLTQ2MzctOGQ0ZC1mODI1ZWYzYzNjZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTQyMzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM5ZWJlOWVlYjUxMWI5YWExZDE0ZTg2NGM2MDM3ZDkyN2I0M2E5ZTliNzIyYWExNjIwMzFkNzg2MWJlZjhkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.M0G4Jr1epP_Nmdz9YGSvCfSliTs-RKai22CzDhoZuvo)

别用对象，用 pinia 的函数写法
