### ISSUE TITLE
关于文档

### ISSUE THREAD

**Issue by bleedkaga** [AttoJS/vue-request#57]
### 问题描述 Problem Description
文档的改进

首先感谢作者创建了这么好的仓库。
但是我发现在文档的示例中偏少了一点，如果能更完善一点就更好了

**Comment by John60676** [comment]
感谢支持😀。后续会加入 CodeSandbox等 在线编辑器的代码块

**Comment by John60676** [comment]
文档已更新，添加了 CodeSandbox 在线示例，代码复制功能。优化了部分示例。
