### ISSUE TITLE
请问在usePagination中是不能用queryKey

### ISSUE THREAD

**Issue by CenGinHong** [AttoJS/vue-request#60]
### 问题描述 Problem Description

在列表上执行更新或者删除时常用queryKey来维护loading状态等。但现在有一个这样的场景，在使用可嵌套表格时，在点击展开时来加载子表格的数据，此时要维护不同的子表格请求状态例如loading等，但usePagination好像不支持qureyKey

### 其他信息 Other information

![1630919897(1)](https://user-images.githubusercontent.com/55742607/132192839-667f6011-25f9-4732-89f6-ef8cf7fd6e87.png)

**Comment by John60676** [comment]
可以提供一个demo吗
