### ISSUE TITLE
🏆 新版本文档更新啦 🔥🔥

### ISSUE THREAD

**Issue by John60676** [AttoJS/vue-request#61]
- 支持代码复制
- 支持在线编辑（CodeSandbox）
- 示例与代码块排版更加美观
- 更贴近业务的示例
- 完全使用 Vue SFC 编写

[文档地址](https://www.attojs.org/) | [国内镜像](https://www.attojs.com/)

❤️ 欢迎大家的支持，有关文档的问题可以在下方讨论

**Comment by daolanfler** [comment]
![image](https://user-images.githubusercontent.com/29777079/134790613-512ba34b-862e-4d77-83ad-14d2f489742f.png)
Just copied the the fist example to my editor, got this error 😂
Maybe we could improve a little bit about the docs typescript lint

**Comment by John60676** [comment]
> ![image](https://user-images.githubusercontent.com/29777079/134790613-512ba34b-862e-4d77-83ad-14d2f489742f.png)
> Just copied the the fist example to my editor, got this error 😂
> Maybe we could improve a little bit about the docs typescript lint

That is not a runable example. Just to show the API.

**Comment by Aliuyanfeng** [comment]
怎么监听接口返回值 我想监听到状态码
