### ISSUE TITLE
useAsyncQuery文件第一次请求时机问题

### ISSUE THREAD

**Issue by zj-wukewei** [AttoJS/vue-request#69]
为什么useAsyncQuery文件中的// initial run 注解的代码是直接运行，而不是在onMounted中？？

**Comment by John60676** [comment]
因为 initial run 是运行在 setup 阶段，相当于 `beforeCreate` 和 `created` 生命周期，这时候发起请求会比 `mounted` 快

**Comment by zj-wukewei** [comment]
但是有些特殊请求就是要在mounted里面请求呢，怎么处理， 就是manual为true，然后手动调用run吗？

**Comment by John60676** [comment]
是的，如果有特殊要求，可以手动调用 run

**Comment by zj-wukewei** [comment]
因为ahooks的时机是useEffect，刚学vue所以才来问一下为什么不是在onMounted中，因为很多情况还是需要用到的就是能拿到ref

**Comment by John60676** [comment]
原因前面也说到了。你这个需求直接使用 `manual` 就好了。假如整个项目都是需要在 `mounted` 阶段请求的，简单封装一层 `useRequest` 就可以了
