### ISSUE TITLE
[Need Help]当多个请求并发的时候，会莫名其妙的卡住，然后请求全部canceled。使用其它方式的并发请求正常。

### ISSUE THREAD

**Issue by mtiger95** [AttoJS/vue-request#70]
### 问题描述 Problem Description
当多个请求并发的时候，会莫名其妙的卡住，然后请求全部canceled。使用其它方式的并发请求正常。

当多个请求并发的时候，会莫名其妙的卡住，然后请求全部canceled。使用其它方式的并发请求正常。

### 其他信息 Other information

![image](https://user-images.githubusercontent.com/23418622/136493554-0b27ee62-d2e3-4065-8a7b-feaac7ab7318.png)

![image](https://user-images.githubusercontent.com/23418622/136493526-de25f37a-fab9-4eba-ba3e-5a7a9e875750.png)

**Comment by John60676** [comment]
先排查一下服务器的问题，来个重现demo？

**Comment by mtiger95** [comment]
谢谢回复，是vue3的问题，https://www.gitmemory.com/issue/vuejs/vue-next/2027/685247838 ，用watch监控了route对象引起的，已解决。
