### ISSUE TITLE
项目打包类型引入报错

### ISSUE THREAD

**Issue by qianphong** [AttoJS/vue-request#71]
### Bug 描述 Bug description

`vue-request` 更新到 `1.2.2`，项目打包提示如下错误

![20211012104035](https://user-images.githubusercontent.com/44841842/136882108-84d68054-74fa-45dd-89b5-7a9db5234073.png)

![20211012104045](https://user-images.githubusercontent.com/44841842/136884823-c986e4bb-e90c-4a89-a8c6-4f56b146aa09.png)

![20211012104049](https://user-images.githubusercontent.com/44841842/136884791-5e4d72fc-92fc-47d1-a829-c8e1997c5711.png)

### 期望结果 Desired result

[src/core/types.ts](https://github.com/AttoJS/vue-request/blob/f3667adb69f5e2f850523aff64017f99babaf4f3/src/core/types.ts) 使用相对路径引入类型
```diff
- import type { LoadMoreExtendsOption } from 'src/useLoadMore';
- import type { PaginationExtendsOption } from 'src/usePagination';

+ import type { LoadMoreExtendsOption } from '../useLoadMore';
+ import type { PaginationExtendsOption } from '../usePagination';
```

**Comment by John60676** [comment]
晚上会发个版
