### ISSUE TITLE
[Need Help]请问如何使data正确显示经过formatResult处理过的ts类型

### ISSUE THREAD

**Issue by web-zhangbo** [AttoJS/vue-request#78]
我继承并重写了axios.get方法，使他返回类型如下
![image](https://user-images.githubusercontent.com/53821155/139613604-a4ec5975-7c71-46eb-a065-ee0a89247886.png)
![image](https://user-images.githubusercontent.com/53821155/139613618-a1c1d42a-ec03-4add-8aa8-2ff9cc131d18.png)
在调用业务接口的时候如下使用
![image](https://user-images.githubusercontent.com/53821155/139613683-9fd8fa14-df9e-4005-85df-bdd9cf8f4404.png)
`findDataSetListByUserId4Select`现在返回的类型是我期待的`Promis<BusinessResponseData<(SelfDataSetPreviewParams | SqlDataSetPreviewParams)[]>>`这些没有问题
vuerequest全局配置如下
![image](https://user-images.githubusercontent.com/53821155/139614013-8810255c-bd27-441a-9177-725eb487e97c.png)
在vue组件中这样使用
![image](https://user-images.githubusercontent.com/53821155/139614077-d57083a4-f814-4b8f-8fa6-d1ac92ea2f78.png)
我希望data的类型应该是经过formatResult转换过的`(SelfDataSetPreviewParams | SqlDataSetPreviewParams)[]`但实际上他是`BusinessResponseData<(SelfDataSetPreviewParams | SqlDataSetPreviewParams)[]>`，请问怎么能让data的类型正确显示为`(SelfDataSetPreviewParams | SqlDataSetPreviewParams)[]`

**Comment by John60676** [comment]
`formatResult` 不支持全局配置的哦，只有这些值才支持全局配置 https://cn.attojs.org/api/global-options.html

**Comment by web-zhangbo** [comment]
我必须要在使用`useRequest`函数时显示传入`rormatResult`函数才能获得我需要的类型，但是这么做全局配置的`formatResult`就失去了意义
![image](https://user-images.githubusercontent.com/53821155/139615329-b9fac33e-18a7-49e9-b048-da23028c7eec.png)

**Comment by web-zhangbo** [comment]
> `formatResult`https://cn.attojs.org/api/global-options.html

但实际上全局配置的`formatResult`在**运行时**是生效的

**Comment by John60676** [comment]
```ts
const { data } = useRequest(SomeFetch, {
  formatResult: res => res.data,
});
```

这样写，就可以拿到你想要的类型了

> > `formatResult`https://cn.attojs.org/api/global-options.html
> 
> 但实际上全局配置的`formatResult`在**运行时**是生效的

那是BUG，后面会过滤掉。至少目前看来 `formatResult` 不应全局配置，这会带来类型推断上的问题

**Comment by web-zhangbo** [comment]
> ```ts
> const { data } = useRequest(SomeFetch, {
>   formatResult: res => res.data,
> });
> ```
> 
> 这样写，就可以拿到你想要的类型了
> 
> > > `formatResult`https://cn.attojs.org/api/global-options.html
> > 
> > 
> > 但实际上全局配置的`formatResult`在**运行时**是生效的
> 
> 那是BUG，后面会过滤掉。至少目前看来 `formatResult` 不应全局配置，这会带来类型推断上的问题

如果formatResult允许全局配置并且可以获得正确的类型那就太好了，谢谢你

**Comment by John60676** [comment]
2.x 将会取消 `formatResult`，因为这会使得有很多很难处理的重载。所以有需要特别处理的数据格式，可以自行在封装 `service` 时处理。

```js
const service = async => {
  const { data } = await axios.get("get/user");
  return {
    sex: data.sex === 1 ? "Male" : "Female",
    ...data,
  };
};

// ....

const { data } = useRequest(service);
```

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
