### ISSUE TITLE
Cancel 未能取消.then方法回调

### ISSUE THREAD

**Issue by dongliangHou** [AttoJS/vue-request#79]
### 代码重现 Reproduce

https://codesandbox.io/s/vue-request-cancel-test-d1zvi?file=/src/App.jsx

### 期望结果 Desired result

cancel 结果后 .then .catch等 方法不再回调

**Comment by John60676** [comment]
因为请求并不是真正的 cancel 了，具体可看[文档](https://www.attojs.com/api/#cancel)。另外不建议直接在 `run` 后面使用 `then` 等操作，有这种需求的可以直接使用 `onSuccess` 或者 `onError`

**Comment by dongliangHou** [comment]
@John60676  恩 主要是看了下 umi-request的表现形式和我们的不太一样。他是 cancel了 就不会.then回调了。 因为有的场景是有顺序的请求的。比如 
```
 const data1= await run1();
 const data2 =await run2();
```
这种情况下 还是 promise方便一些。  感谢您的回答

**Comment by John60676** [comment]
[依赖请求](https://www.attojs.com/guide/documentation/ready.html) 或者是 [依赖刷新](https://www.attojs.com/guide/documentation/refreshDeps.html) 可能可以满足你的需求

**Comment by dongliangHou** [comment]
好的 谢谢。 场景是有的时候 顺序还不太一样。 各种组合 。我克服吧 哈哈
