### ISSUE TITLE
关于取值的问题

### ISSUE THREAD

**Issue by matrix-zyh** [AttoJS/vue-request#81]
### 通过 useRequest 拿到的值，怎么都获取不到

我使用 `函数` 的方式使用 `useRequest`，但是我的接口返回的数据是一个对象类型的，我使用 data ，怎么都获取不到我的数据。

我能请求到，这样写也没问题
![code1](https://www.vuejs.love/images/cache/code1.png)
![console1](https://www.vuejs.love/images/cache/console1.png)

但是当我想去其中的某一项时，他就会报错
![code2](https://www.vuejs.love/images/cache/code2.png)
![console2](https://www.vuejs.love/images/cache/console2.png)

不论我使用什么方式去取这个 data 对象下的数据，始终都无法取到，请问是我取的方式不对吗？求指点。

**Comment by matrix-zyh** [comment]
### 代码是这样的

```vue
<template>
  <div>{{ data }}</div>
</template>

<script lang="ts" setup>
  import { onMounted } from 'vue';
  import { login } from '/@/api/service/basic';
  import { useRequest } from 'vue-request';

  const { data, loading, error, run } = useRequest(login);

  onMounted(() => {
    run();
    console.log('data: ', data);
    console.log('loading: ', loading);
    console.log('error: ', error);
  });
</script>
```

**Comment by benny-eu** [comment]
如果请求未完成，`data`为`undefined`。

可改为：

```vue
<template>
  <div>{{ data }}</div>
</template>

<script lang="ts" setup>
  import { onMounted } from 'vue';
  import { login } from '/@/api/service/basic';
  import { useRequest } from 'vue-request';

  const { data, loading, error, run } = useRequest(login);

  onMounted(async () => {
    await run();
    console.log('data: ', data);
    console.log('loading: ', loading);
    console.log('error: ', error);
  });
</script>
```

**Comment by matrix-zyh** [comment]
作者您好！
我有两个问题，麻烦请教一下您。
第一：如果这样的话，那是不是说明，我在手动执行 run 的时候，都需要加上 async / await 之后才能够正确的取到 data 里面的数据呢？
第二：根据您的指导，我尝试了一下，在 onMounted 加上 async / await 之后打印 data.value.id
的确拿到了数据，但是在 Template 模版中 使用 data.id 或者 data.value.id 仍然是不可行的，还是报的那个错误，我该如何在
Template 模版中直接使用到 data 的值呢？求指教，感谢！
祝您拥有美好的一天！

Benny Eu ***@***.***> 于2021年12月15日周三 09:40写道：

**Comment by John60676** [comment]
template 渲染时，你的请求还没拿到结果，所以导致 `data` 是 `undefined`，所以要不就在 template 里判断一下 `data` 是否 `undefined`，要不就 用 `computed`

```html
<template>
  <div>{{ templateData.id }}</div>
</template>
```

```ts
const templateData = computed(() => data.value)
```

**Comment by matrix-zyh** [comment]
您好，请教一下，这样真的好使吗？我在代码中使用了 computed 的方式，但是发现还是不行，还是报 “ Cannot read properties
of undefined (reading 'id') ”，也就是说  我通过计算属性拿到的 templateData 在模版中使用，前期拿到的还是
undefined 的，即使我 const templateData = computed(() => { retrun data ? data.value
: {} }) 也依旧是不行的，想请教一下，是为什么呢？我的是真实的接口请求。

John ***@***.***> 于2021年12月15日周三 12:35写道：

**Comment by John60676** [comment]
```ts
const templateData = computed(() => { retrun data.value ? data.value : {} })
```

**Comment by matrix-zyh** [comment]
原来是这样，感谢您的解答，谢谢！

John ***@***.***> 于2021年12月15日周三 15:16写道：
