### ISSUE TITLE
是否可以新增“请求去重功能”这一配置项

### ISSUE THREAD

**Issue by lsd1** [AttoJS/vue-request#83]
### 需求描述 Feature Description
场景：如果请求耗时5秒，用户在等待中发起了条件不一样的第二次请求，但是可能第二次请求结果比较快，第一次请求结果返回比较慢，慢的请求结果会覆盖快的请求结果，用户看到的结果是第一次请求的结果

### 建议的解决方案 Proposed Solution
希望可以新增配置项：请求去重功能
区分为：
强去重模式：uniqueModel: 'force'
弱去重模式：uniqueModel: 'weak'
默认不去重模式：uniqueModel: 'not'

强去重模式是只有请求的url、方法、参数（post和get参数）完全一样才会取消上一次的请求
弱去重模式是只有请求的url、方法一样时会取消上一次的请求
不去重模式是不取消请求

**Comment by keuby** [comment]
@lsd1 可能不是一个通用的功能。这种去重模式，只适用于传入 config 的方式发送的请求，如果传入的是一个方法或者是一个 promise 对象则无效。

对于你当前的需求，我认为可以结合 loading 状态来解决。比如在执行 run 方法前，先判断一下 loading 是否为true，若为 true 则先调用一下 cancel 方法，然后再调用 run 方法就可以解决

**Comment by John60676** [comment]
其实是有个 [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) 可以实现取消请求，我在考虑这东西是否需要内置

**Comment by keuby** [comment]
> 其实是有个 [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) 可以实现取消请求，我在考虑这东西是否需要内置

我不太确定你想要实现成什么样子。从我查阅的资料来看，在当前项目中，目前能使用的也就只有 fetch 方法，而传入一个 function 或者 Promise 作为 service 的场景下难以使用这个 AbortController。而且这个东西存在一定的浏览器兼容性问题，如果支持这个的话，会为后续迁移 vue2 造成一定的影响。

**Comment by John60676** [comment]
该功能会在 2.x 实现

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
