### ISSUE TITLE
[Need Help]为什么缓存和保鲜都无效呢？

### ISSUE THREAD

**Issue by allenlinc** [AttoJS/vue-request#85]
### 问题描述 Problem Description
为什么缓存无效呢？manual  true和false都试过。都是直接发送ajax，缓存和保鲜设置不设置没任何区别。

`<script lang="ts">
import { defineComponent } from "vue";
import { useRequest } from "vue-request";
import axios from "axios";

export default defineComponent({
  name: "TestItem",
  setup() {
    const service = (userName: string) => {
      return axios.get("http://dns.top8.site:4000/mock/110/mytest", {});
    };
    const { data, loading, error, run } = useRequest(service, {
      manual: false,
      pollingInterval: 1000,
      // pollingWhenHidden: true,
      cacheKey: "date",
      // cacheTime: 300000, // 5 minutes
      staleTime: 30000,
      onSuccess: (data) => {},
    });

    return { data, loading, error, run };
  },
});
</script>`

**Comment by John60676** [comment]
请注意看文档哦，缓存不是不会发起请求

![image](https://user-images.githubusercontent.com/21698973/148481006-6977d61a-0c4d-42eb-8036-016aad3c7e33.png)

**Comment by johanninos** [comment]
<img width="856" alt="截屏2022-07-06 12 23 34" src="https://user-images.githubusercontent.com/6007878/177467875-43d7eea5-93a6-4577-9dd8-9a097719d5a2.png">
可是 staleTime文档不是这么说的呀

**Comment by John60676** [comment]
「当缓存启用后 VueRequest 会把当前请求的结果缓存下来，**等到下次该组件初始化时，亦或者另外一个设置了同样 cacheKey 的请求初始化时**，如果有缓存，则会优先返回缓存的数据」

在 v1 中，缓存复用只会出现在 “组件初始化时”，`staleTime` 只是决定会不会发起新的请求。一切的前提是触发了缓存复用

**Comment by YuanZhencai** [comment]
只能是组件初始化时吗？能在方法中使用吗？在缓存时间内多次调用方法，返回同样的结果
