### ISSUE TITLE
[Need Help]What's the difference between vue-request and swrv

### ISSUE THREAD

**Issue by wanliyunyan** [AttoJS/vue-request#89]
### 问题描述 Problem Description
I want to choose a lib for development，but hesitate in these two libs，so who can tell me the difference???

**Comment by John60676** [comment]
你可以对比一下文档，其实我们刚开始的版本也有参考 swr 的功能，所以 swr 有的功能，基本上我们也有。除了这些以外，我们还有分页以及加载更多的扩展功能，能进一步减少业务代码的编写。

**Comment by wanliyunyan** [comment]
好的，谢谢，经过最终的研究我决定选这个lib，虽然star比那么少了点，但是文档比那个全面的多，同时中文环境让人喜欢
