### ISSUE TITLE
问一下请求回来是json的数据

### ISSUE THREAD

**Issue by checkwoodson** [AttoJS/vue-request#90]
请求回来是json 的数据被代理了以后，我在js中如何转成JSON.parse格式，如何对返回的数据进行操作和处理的。

**Comment by John60676** [comment]
没看懂，来个demo？

**Comment by checkwoodson** [comment]
就比如函数实例中：
`
const { data, run } = useRequest(getUser, {
  defaultParams: [{ name: '马冬梅' }],
});

run('张三');
`
我吸出来的data是后台返回的数据嘛， 那我后台返回的数据该如何进行修改。因为是已经被ref所代理的。就好奇这数据能改吗。

**Comment by John60676** [comment]
`mutate()` 文档地址：https://www.attojs.com/guide/documentation/mutation.html

**Comment by checkwoodson** [comment]
那就是说我后台请求的数据要处理的话要通过计算属性对数据进行修改了。 vueuse返回来的数据也是用ref代理的。那么如果说不想那么麻烦 还是返回的数据处理好了在把数据进行代理了。

**Comment by John60676** [comment]
我还是没搞懂你想问什么，如果只是说，想从接口拿到数据后，对 data 进行修改的话，用 mutate 就可以了，或者自己用个 computed 包装一下去修改也可以

**Comment by keuby** [comment]
> 就比如函数实例中： ` const { data, run } = useRequest(getUser, { defaultParams: [{ name: '马冬梅' }], });
> 
> run('张三'); ` 我吸出来的data是后台返回的数据嘛， 那我后台返回的数据该如何进行修改。因为是已经被ref所代理的。就好奇这数据能改吗。

我猜测你的意思是说，想对数据返回值做进一步处理，从而使拿到的 data 是处理之后的数据，可以考虑使用 [formtResult](https://www.attojs.com/api/#formatresult)

**Comment by checkwoodson** [comment]
没毛病了，就是这个意思 感谢了。那就没错了。
