### ISSUE TITLE
[Need Help] const { data } = useRequest(testService}，data有ref类型的值，但是data.value是undefined

### ISSUE THREAD

**Issue by wanliyunyan** [AttoJS/vue-request#95]
### 问题描述 Problem Description

```
<template>
  <div v-for="item in list" :key="item.id">
    {{ item.name }}
  </div>
</template>

<script lang="ts" setup>
import axios from "axios";
import { computed } from "vue";
import { useRequest } from "vue-request";

function testService(params: { page?: number; limit?: number }) {
  return axios.get("https://61273138c2e8920017bc0b3c.mockapi.io/api/users", {
    params,
  });
}

const { data } = useRequest(testService, {
  defaultParams: [
    {
      limit: 5,
    },
  ],
});

console.log(data); // 有值
console.log(data.value); // undefined
const list = computed(() => data.value?.data.data || []); // 因为data.value为undefined，所以list也就是[]
</script>
```

我这段代码基本就是从您的例子中粘贴过来的，看了很久的文档，一直拿不到正确的值，我不知道我错在哪里，请您指导一下，非常感谢
![image](https://user-images.githubusercontent.com/10751248/150742057-3e728271-dd6b-47fa-8ffc-4ba67c8f93aa.png)

**Comment by John60676** [comment]
参考  https://codesandbox.io/s/runtime-smoke-d9h4b?file=/src/App.vue

```js
console.log(data.value); // 请求是异步的，所以执行这行代码时，请求还没结束，因此是undefined
console.log(data); // 同上一行，但是log有结果是因为对象引用问题
```

**Comment by wanliyunyan** [comment]
我已经明白您说的对象引用的意思了，这代码的意思是利用computed计算属性，拿到最终的值，但是
```
const list = computed(
      () => (data.value && data.value.data && data.value.data.data) || []
 );
```
我按照您说的，这样写，list依然拿到的是[]，还有您给的例子，报错了.....
![image](https://user-images.githubusercontent.com/10751248/150746808-0bd1cf43-edbc-45d8-bffe-384ceb97c4a6.png)

**Comment by John60676** [comment]
codesandbox 的 bug，刷新一下就好了的

**Comment by wanliyunyan** [comment]
![image](https://user-images.githubusercontent.com/10751248/150754822-910bb8b8-234f-4aee-bbcc-6d33dcd0282d.png)

![image](https://user-images.githubusercontent.com/10751248/150754904-af8f5a34-a333-4f84-b7a0-927aad2cf929.png)


一模一样的代码，codesandbox 确实是有值了。但是我这.....还是不显示......，要不我在github上搞一个项目，您看看我代码？？？？？

**Comment by John60676** [comment]
来个可复现的仓库吧

**Comment by wanliyunyan** [comment]
同样的代码放在我同事电脑上就出来了，绝了。我自己先研究一下.......

**Comment by wanliyunyan** [comment]
我把node_mudules 删了，代码也是重新拉的，好使了，这个诡异的问题，我已经复现不了了，我感觉问题就是出现在node_mudules 里了，谢谢啦，麻烦你这么长时间
