### ISSUE TITLE
[Need Help]

### ISSUE THREAD

**Issue by zxxzzzzz** [AttoJS/vue-request#96]
### 问题描述 Problem Description
请问为什么用了cacheKey的请求，当提供了params时，要复用之前cache的params? 比如下面第二个请求的参数还是`{ limit: 1, offset: 10 }`
```javascript
useRequest(getSchools, {
  cacheKey:'school',
  defaultParams: [{ limit: 1, offset: 10 }],
})

useRequest(getSchools, {
  cacheKey:'school',
  defaultParams: [{ limit: 1, offset: 12 }],
})
```
是否可以在后面请求添加了defaultParams参数时，把先前cache的请求的params覆盖掉。

**Comment by John60676** [comment]
有缓存的情况下，是优先使用缓存的。如果你要覆盖掉，就要触发一次 `run`
