### ISSUE TITLE
[Need Help]能不能提供一个选项来标识返回的数据不用变成响应式的

### ISSUE THREAD

**Issue by laddish** [AttoJS/vue-request#98]
### 问题描述 Problem Description
这个库的许多功能都很棒！我在思考可不可以有一个选项来标识返回的数据不变成响应式的

我知道这个库的特点是默认返回的数据都是响应式的，这也是我被吸引的首要原因。
但是我现在遇到一种情况，
当我获取一个长数组去渲染页面的时候，
（注：长数组：大于5000条数据，每条数据里面又包含一些对象；渲染页面：根据数据在canvas里面画图，不是直接渲染列表生成dom节点，长数组量是业务需求的）
当我面对这样一个长数组，我不需要它是响应式的（我其实好奇这么多数据去遍历响应式能花费多长时间），所以当我使用的时候需要把他们markRaw，我当然可以直接不套一层vuerequest去请求，但是这个库封装的其他特性很有用。
我看了文档，没有找到可以实现一个选项让数据不需要是响应式的，默认返回的数据都是响应式的，这在几乎所有情况下都很有用。

### 其他信息 Other information
我不清楚这个需求是否可行，是否有可能影响到其他特性？

我请求的数据默认都变成了响应式
![Snipaste_2022-02-08_16-54-46](https://user-images.githubusercontent.com/49431692/152953715-a8765e22-09b5-4a5c-8505-a78abae93993.png)

我使用的时候需要markRaw
![Snipaste_2022-02-08_16-56-14](https://user-images.githubusercontent.com/49431692/152953783-251b56f5-4060-4e7f-afab-a815c2ea4995.png)

**Comment by John60676** [comment]
很有意思的想法👍 ，最近在写2.x版本，这个功能可以考虑添加。目前看来没啥大问题，不过最终还是得看会不会影响一些新加的功能

**Comment by keuby** [comment]
几万条数据这个级别，遍历数据的效率据我观察还是比较快的，性能方面应该不会有太大影响，不过这个建议我觉得是有必要的。不过我任务不需要完全去除响应式，可以通过选项开控制是使用 ref 还是 shallowRef 来创建 data 变量应该会更好一些，使用 shallowRef 创建的 ref 变量，取出里面的值时，不会对里面的对象使用 reactive 包裹

**Comment by John60676** [comment]
> 几万条数据这个级别，遍历数据的效率据我观察还是比较快的，性能方面应该不会有太大影响，不过这个建议我觉得是有必要的。可以通过选项控制是使用 ref 还是 shallowRef 来创建 data 变量，使用 shallowRef 创建的 ref 变量，不会对里面的对象使用 toReactive 处理

是的，如果后面实现的话，也是考虑用 shallowRef

**Comment by laddish** [comment]
谢谢解答~

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
