### ISSUE TITLE
除了run函数外，能不能像ahooks一样返回一个Promise的异步函数，用于自己捕获异常,目前run函数返回的promise的catch捕获不到异常，只有在onError中才能捕获到异常

### ISSUE THREAD

**Issue by Mrzbf** [AttoJS/vue-request#99]
const { loading, runAsync } = useRequest(dosomething, {
    manual: true,
  });

  const onClick = async () => {
    try {
      await runAsync(state);
      doOther()
    } catch (error) {
      message.error(error.message);
    }
  };

**Comment by keuby** [comment]
可以有一个替代方案

```ts
const { loading, run, error } = useRequest(dosomething, {
    manual: true,
});

const onClick = async () => {
    await run(state);
    if (error.value) {
        message.error(error.message);
    }
}
```

**Comment by John60676** [comment]
这个功能 2.x 已经实现了

**Comment by keuby** [comment]
@John60676 大佬，可以透露一下 2.x 都新增了哪些新功能么？:dog:

**Comment by John60676** [comment]
> @John60676 大佬，可以透露一下 2.x 都新增了哪些新功能么？🐶

晚些会发个 roadmap 出来的，目前有些功能还在尝试中，也可以留意一下 next 分支

**Comment by Mrzbf** [comment]
> 可以有一个替代方案
> 
> ```ts
> const { loading, run, error } = useRequest(dosomething, {
>     manual: true,
> });
> 
> const onClick = async () => {
>     await run(state);
>     if (error.value) {
>         message.error(error.message);
>     }
> }
> ```

你这种方案好像不太可行，await执行完后error.value的值为空，而且error状态会被缓存

**Comment by keuby** [comment]
@Mrzbf 我这边是可以的，不知道你那边是怎么做的，可以提供一个demo吗？

**Comment by 907014165** [comment]
> 这个功能 2.x 已经实现了

请问2.x有计划什么时候上吗

**Comment by John60676** [comment]
这个问题我们已经在 v2 版本处理了，目前 v2 版本已经发布 rc 版本。

欢迎试用。

文档：https://next.attojs.com
源码：https://github.com/AttoJS/vue-request/tree/next

安装最新版本

```sh
$ npm install vue-request@next
# or
$ yarn add vue-request@next
# or
$ pnpm install vue-request@next
```
